### ISSUE TITLE
Updating Labels

### ISSUE THREAD

**Issue by Sahin-Albayram** [bounswe/bounswe2023group2#10]
Some new label is needed.
* status : In progress label

**Comment by bgmrsln** [comment]
I think we should also add:
- effort : 1
- effort : 3
- effort : 5
- effort : 7
labels

**Comment by Sahin-Albayram** [comment]
> I think we should also add:
> 
> * effort : 1
> * effort : 3
> * effort : 5
> * effort : 7
>   labels

What should the range of the effort scale be?
