### ISSUE TITLE
Class Diagram for Event

### ISSUE THREAD

**Issue by mervegrbz** [bounswe/bounswe2023group2#100]
### Issue Description

Event has many attributes and they will be used in many functionality:
- type
- date
- location
- creator
- get_event()
- create_event()
- ...

### Deadline of the Issue

09.04.2023

### Reviewer

Ramazan Burak Sarıtaş

**Comment by mehmetkuzu** [comment]
check: 
https://lucid.app/lucidchart/afae99ec-6341-48cb-8ecc-38b905696b64/edit?view_items=pK~MeBuNF1ro&invitationId=inv_70642368-fc2b-4d12-ae80-646f21713db8

**Comment by mervegrbz** [comment]
I have done the task and we reviewed with Burak.
