### ISSUE TITLE
Class Diagram for Need

### ISSUE THREAD

**Issue by halilgurbuz** [bounswe/bounswe2023group2#101]
### Issue Description

Need has many attributes and they will be used in many functionality:

type
date
location
creator
get_need()
create_need()
...

### Deadline of the Issue

09.04.2023

### Reviewer

Begüm Arslan

**Comment by mehmetkuzu** [comment]
check:
https://lucid.app/lucidchart/afae99ec-6341-48cb-8ecc-38b905696b64/edit?view_items=pK~MeBuNF1ro&invitationId=inv_70642368-fc2b-4d12-ae80-646f21713db8

**Comment by mervegrbz** [comment]
I have merged this to the others? Can you check @halilgurbuz

**Comment by halilgurbuz** [comment]
I completed this. Can you review @bgmrsln ?

**Comment by bgmrsln** [comment]
closing the issue
