### ISSUE TITLE
Class diagram for Resource

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#103]
### Issue Description

Create class diagrams for resource class.

### Deadline of the Issue

9.4.23

### Reviewer

Ramazan Burak Sarıtaş

**Comment by mehmetkuzu** [comment]
check this
https://lucid.app/lucidchart/afae99ec-6341-48cb-8ecc-38b905696b64/edit?view_items=pK~MeBuNF1ro&invitationId=inv_70642368-fc2b-4d12-ae80-646f21713db8
