### ISSUE TITLE
Class diagram for Action

### ISSUE THREAD

**Issue by mervegrbz** [bounswe/bounswe2023group2#104]
### Issue Description

Action is a bit different from other activities, since it will use the other type of activities.
- used_resources
- created_resources
- created_needs
- related_event 
- ...

### Deadline of the Issue

10.04.2023

### Reviewer

Cahid Enes Keleş

**Comment by arasgungore** [comment]
I have thought of storing the related activity type and the status of the activity (created, used, finished, etc.) as Enum attributes.

**Comment by cahidenes** [comment]
What are related activity type and related activity status?

**Comment by cahidenes** [comment]
I made some edits. This issue can be closed now.
