### ISSUE TITLE
Last edit mockups and requirements

### ISSUE THREAD

**Issue by egecans** [bounswe/bounswe2023group2#105]
### Issue Description

Requirements and mock-ups must be revised and edited again after a detailed use-case diagram. We have a lot to do especially in mock-ups. We should go on with Figma instead of diagrams.net. I assign myself to this for now, but we have to do this together. It's not as easy as one person can do. So, please participate in and discuss what we can do and explain what you did under this issue.

### Deadline of the Issue

10.03.2023

### Reviewer

Merve Gürbüz

**Comment by mehmetkuzu** [comment]
I will register to figma?

**Comment by egecans** [comment]
I'm starting to edit the requirements. If you have any ideas state them below this issue please.

**Comment by egecans** [comment]
I think I finished the requirements please review them if you have enough time :,). And check whether there was a typo or missing information

**Comment by mervegrbz** [comment]
I have added the mock up and usee scenario related to Map usage #154

**Comment by egecans** [comment]
Some of the Mock-ups couldn't be finished, but most of them are appended to the mock-up page. We can use them as a user scenario as well.
