### ISSUE TITLE
Create registration related sequence diagram

### ISSUE THREAD

**Issue by mervegrbz** [bounswe/bounswe2023group2#107]
### Issue Description

We have defined use cases and classes before in  the diagrams. Sequence diagrams for this use cases should be written

### Deadline of the Issue

10.04.2023

### Reviewer

Begüm Arslan

**Comment by mervegrbz** [comment]
I have added login part and @mehmetkuzu added signup part.

**Comment by bgmrsln** [comment]
<img width="625" alt="image" src="https://user-images.githubusercontent.com/53114791/230902104-1ccd2746-e1ea-4209-b370-aa1d3dcb863e.png">
<img width="622" alt="image" src="https://user-images.githubusercontent.com/53114791/230902151-3386d9f4-a416-485a-84ea-6397d1eaba70.png">
Seems done, closing the issue
