### ISSUE TITLE
Milestone 1 Report - Evaluation of tools and processes

### ISSUE THREAD

**Issue by halilgurbuz** [bounswe/bounswe2023group2#115]
### Issue Description

Evaluation of tools and processes should be prepared.

### Deadline of the Issue

10.04.2023 23.59

### Reviewer

None

**Comment by cahidenes** [comment]
Written [here](https://github.com/bounswe/bounswe2023group2/wiki/Tmp---Tools-we-used). This page will later be merged with the main report.
