### ISSUE TITLE
 Sequence diagrams - Need, Resource

### ISSUE THREAD

**Issue by mervegrbz** [bounswe/bounswe2023group2#117]
### Issue Description

Need and resource have similar sequences so it is good to do them together.
- Delete
- add 
- update
-  report

### Deadline of the Issue

10.04.2023

### Reviewer

Begüm Arslan

**Comment by halilgurbuz** [comment]
Can you review and close if ok @bgmrsln ?

**Comment by halilgurbuz** [comment]
> It seems like you did not add parameters inside the functions here. Not sure which way is correct?

I updated them accordingly.
