### ISSUE TITLE
Sequence diagram-Admin specific

### ISSUE THREAD

**Issue by mervegrbz** [bounswe/bounswe2023group2#119]
### Issue Description

Admin has some use cases apart from others:
- delete user
- give credibility

### Deadline of the Issue

10.04.2023

### Reviewer

Ramazan Burak Sarıtaş

**Comment by mervegrbz** [comment]
I am taking the issue to me and sahin since we need to finish all the sequence diagrams today.

**Comment by Sahin-Albayram** [comment]
Done.
<img width="623" alt="image" src="https://user-images.githubusercontent.com/94677441/230950787-54a2ab53-5259-490a-981d-7d6fb5a29799.png">
<img width="630" alt="image" src="https://user-images.githubusercontent.com/94677441/230950817-3e89843f-c142-448f-9088-9770fd5c1dfa.png">
<img width="639" alt="image" src="https://user-images.githubusercontent.com/94677441/230950867-12973d27-3479-47c6-9178-2e0ab8324d41.png">
