### ISSUE TITLE
Sequence Diagrams - Notifications 

### ISSUE THREAD

**Issue by mervegrbz** [bounswe/bounswe2023group2#120]
### Issue Description

Notifications:
- can be created
- deleted
- published
...

### Deadline of the Issue

10.04.2023

### Reviewer

Egecan Serbester

**Comment by bgmrsln** [comment]
<img width="394" alt="image" src="https://user-images.githubusercontent.com/53114791/230882682-60dd313e-e6bf-4ecb-bc47-207eee2066ee.png">
<img width="299" alt="image" src="https://user-images.githubusercontent.com/53114791/230882709-77fb1e2b-a251-49bd-81ad-971d9e238627.png">
Can you review @egecans ?
