### ISSUE TITLE
Create User Scenarios 

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#136]
### Issue Description

Following user scenerios can be written:
- [x] #152
- [x] #153
- [x] Subscribing to a notification topic.

### Deadline of the Issue

11.04.23

### Reviewer

Merve Gürbüz

**Comment by bgmrsln** [comment]
Created the user scenerio for [notifications](https://github.com/bounswe/bounswe2023group2/wiki/Scenerio-1/_edit).

**Comment by cahidenes** [comment]
All scenarios are done!
