### ISSUE TITLE
Delete Emergency

### ISSUE THREAD

**Issue by egecans** [bounswe/bounswe2023group2#137]
### Issue Description

The most suitable way to delete an emergency is to report it to the admin and the admin can delete it according to reports I think. Because we don't have enough time I will add this to the requirements, the use-case class diagram and class sequence diagram. Please prepare mock-ups according to this.

### Deadline of the Issue

10.04.2023

### Reviewer

Ömer Şahin Albayram

**Comment by rburaksaritas** [comment]
I will take the Class Diagram part of the Emergency. 
Tracking at #139

**Comment by egecans** [comment]
I close this since it's finished.
