### ISSUE TITLE
Sequence Diagram Event Specific Diagrams

### ISSUE THREAD

**Issue by cahidenes** [bounswe/bounswe2023group2#146]
### Issue Description

Following event specific diagrams should be drawn:

- [ ] Create new event
- [ ] Edit event
- [ ] View event
- [ ] Report event
- [ ] Upvote event

It is important to check if the diagram is already drawn, and start to draw.

### Deadline of the Issue

10.04.2023

### Reviewer

None

**Comment by mehmetkuzu** [comment]
https://lucid.app/lucidchart/12dfcb9b-df14-4b9f-a228-58b117165a21/edit?invitationId=inv_8a88f82c-9cd0-46dc-a8e0-b570787cd833&page=peJNy0zslA.c#
