### ISSUE TITLE
Sequence Diagram Authentication Related Diagrams

### ISSUE THREAD

**Issue by cahidenes** [bounswe/bounswe2023group2#148]
### Issue Description

Following diagrams should be drawn:

- [x] Register
- [x] Reset password (using email)
- [x] Login
- [x] Log out

It is important to check if the diagram is already drawn and then start to draw.

### Deadline of the Issue

04.10.2023

### Reviewer

None

**Comment by rburaksaritas** [comment]
Register, Login and Reset Password Sequence Diagrams are already present. 
I will add the Log out diagram.

**Comment by rburaksaritas** [comment]
I added the Log out Sequence Diagram.
