### ISSUE TITLE
Sequence Diagram Notification Related Diagrams

### ISSUE THREAD

**Issue by cahidenes** [bounswe/bounswe2023group2#150]
### Issue Description

Following diagrams should be drawn:

- [x] Edit notification settings
- [x] Add new notification topic
- [x] Delete notification request
- [x] Receive notification (?)

It is important to check if the diagram is already drawn and then start to draw.

### Deadline of the Issue

04.10.2023

### Reviewer

None

**Comment by rburaksaritas** [comment]
Existing notification-related sequence diagrams seems to be inclusive of the list.  

I think adding and deleting a notification topic include "edit notification settings".
