### ISSUE TITLE
Sequence Diagram Map, Filter and Sort Related Diagrams

### ISSUE THREAD

**Issue by cahidenes** [bounswe/bounswe2023group2#151]
### Issue Description

Following diagrams should be drawn:

- [x] View activities on map
- [x] Search activity 
- [x] Go to location
- [x] Search user
- [x] Search emergency

It is important to check if the diagram is already drawn and then start to draw.

### Deadline of the Issue

04.10.2023

### Reviewer

None

**Comment by Sahin-Albayram** [comment]
All done 
<img width="627" alt="image" src="https://user-images.githubusercontent.com/94677441/230962765-d1212f02-4f3f-4c8e-985c-e2e13e63fcff.png">
<img width="642" alt="image" src="https://user-images.githubusercontent.com/94677441/230962829-51711009-cdf5-4695-bdc9-273e57371c17.png">
<img width="870" alt="image" src="https://user-images.githubusercontent.com/94677441/230962945-78ebcbf2-b24a-4dcf-8aab-d2976a52aef7.png">
<img width="864" alt="image" src="https://user-images.githubusercontent.com/94677441/230963329-4da73dc8-b7e8-45cf-ae8c-77ec1e91da01.png">
