### ISSUE TITLE
User Scenarious: Creating an activity.

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#153]
A scenario related to creating an activity should be made. The scenario should contain the following parts:

- [x] The user, persona
- [x] User goals
- [x] Preconditions
- [x] Acceptance Criteria
- [x] Mockup

**Comment by cahidenes** [comment]
Scenario is done. Here is the [link](https://github.com/bounswe/bounswe2023group2/wiki/Scenario-2)
