### ISSUE TITLE
Milestone 2 Tools Discussion

### ISSUE THREAD

**Issue by egecans** [bounswe/bounswe2023group2#160]
### Issue Description

I created some discussions [for APIs](https://github.com/bounswe/bounswe2023group2/discussions/157),  [web service](https://github.com/bounswe/bounswe2023group2/discussions/158) and [git actions](https://github.com/bounswe/bounswe2023group2/discussions/159). You can share your ideas below these topics.
Additionally, you should revise the [meeting 9 notes](https://github.com/bounswe/bounswe2023group2/wiki/Meeting-%239) and learn the tools that we will use in this milestone. We will meet on Tuesday evening to discuss and pick the tools that we will use.

### Deadline of the Issue

18.04.2023

### Reviewer

Merve Gürbüz

**Comment by mervegrbz** [comment]
I am closing the issue, tools decided
