### ISSUE TITLE
Open Practice-App Project

### ISSUE THREAD

**Issue by egecans** [bounswe/bounswe2023group2#161]
### Issue Description

We need to open a project for Practice App on Milestone 2. We should do all push, commit and merge things related to Practice App to that Project. 

### Deadline of the Issue

18.03.2023

### Reviewer

Cahid Enes Keleş

**Comment by bgmrsln** [comment]
Created the [practice-app](https://github.com/bounswe/bounswe2023group2/tree/main/practice-app) folder with a Readme file in it. I also created a project to keep track of issues, tasks related to this project. I am not sure if I should have created a new repository named practice-app and add it as a submodule to our current repo. Other than that the work is done. Can you review @cahidenes

**Comment by mervegrbz** [comment]
Milestone description says to open in the same repository so it seems fine

> Created the [practice-app](https://github.com/bounswe/bounswe2023group2/tree/main/practice-app) folder with a Readme file in it. I also created a project to keep track of issues, tasks related to this project. I am not sure if I should have created a new repository named practice-app and add it as a submodule to our current repo. Other than that the work is done. Can you review @cahidenes
