### ISSUE TITLE
Pick which Functionality to Develop on Milestone 2

### ISSUE THREAD

**Issue by egecans** [bounswe/bounswe2023group2#162]
### Issue Description

According to Milestone 2 documentation we should develop functionality with APIs that we will use in the real project with this explanation:
Each member will utilize at least one API (of your choice) as well as offer an API function.
That means every team member will consume an API call result and also create an API function.
The API you will develop should be useful for your own team project. You are free to design the
specific functionality that your API will offer – so long as it is well-documented and is meaningful
for your course project.

So we need to pick any functionality to develop. If you decide to develop a functionality before anyone else please append them next to your names.
 Name | Will Use External API | Expose Functionality |
:-------------:|:-------------:|:-------------:|
 Aras Güngöre  | TimeZoneDB API | Get time zone of the disaster location |
Begüm Arslan  | Firebase API(failed) OpenWeatherAPI  | sending notifications when subscribed to a topic(failed) Show weather data for a location  |
Cahid Enes Keleş | UUID Generator API | Adding new activity to the database |
Egecan Serbester | Twilio API | Send SMS to users when they are registered  |
Halil İbrahim Gürbüz | SendGrid API | Send Email Report to admin |
Hasan Bingölbali |  |  |
Mehmet Emin İpekdal |  |  |
Mehmet Kuzulugil | Twitter API | GET request to collect related twitter info<br> POST request to verify an info  |
Merve Gürbüz |  |  |
Ömer Şahin Albayram |  geolocation API| Mapping visualization of activities  |
Ramazan Burak Sarıtaş | openAQ API | Filter & Sort |

#### Open (Ideas)
Will Use External API | Expose Functionality | Proposed by |
:-------------:|:-------------:|:-------------:|
Google API for spreadsheets | Use google forms to collect input to the system | Mehmet K. |
| Some search API | Searching an activity from the database | Cahid |

### Deadline of the Issue

18.03.2023

### Reviewer

Merve Gürbüz

**Comment by mervegrbz** [comment]
[Disaster Tracker](https://eonet.gsfc.nasa.gov/api/v3/events) I have found this API. Maybe one of us wants to use it

**Comment by bgmrsln** [comment]
### Some related API s
1. Google Maps API:
Title: Google Maps API
**Subtitle: Building location-based applications**
    
    Content:
    
    - Embedding maps
    - Searching for locations
    - Obtaining driving directions
2. Twilio API for SMS:
Title: Twilio API for SMS
**Subtitle: Sending and receiving SMS messages**
    
    Content:
    
    - Sending alerts and notifications to users
    - Free trial account with $15 credit
    - Verification code functionality
3. OpenWeatherMap API:
Title: OpenWeatherMap API
Subtitle: Displaying weather data and forecasts
    
    Content:
    
    - Current and forecasted weather conditions
    - Integration into your application
4. SendGrid API:
Title: SendGrid API
Subtitle: **Cloud-based email service**
    
    Content:
    
    - Sending and receiving emails in your application
    - Integration with popular programming languages
5. **IBM Watson Natural Language Understanding API:**
Title: IBM Watson Natural Language Understanding API
Subtitle: Analyzing text and extracting insights
    
    Content:
    
    - Sentiment analysis
    - Entity recognition
    - Keyword extraction
    - Disaster-related text data analysis
6. Firebase Cloud Messaging API:
Title: Firebase Cloud Messaging API
**Subtitle: Sending notifications to users**
    
    Content:
    
    - Integration into your application
    - Targeted notifications
    - Notification customization options
7. Nexmo API for SMS:
Title: Nexmo API for SMS
Subtitle: Sending and receiving SMS messages
    
    Content:
    
    - Free trial account with access to their SMS API
    - Verification code functionality
8. Vonage API for SMS:
Title: Vonage API for SMS
Subtitle: Sending and receiving SMS messages
    
    Content:
    
    - Free plan with access to their SMS API (formerly Nexmo)
    - Includes up to 50 messages per month
9. TextMagic API for SMS:
Title: TextMagic API for SMS
Subtitle: Sending and receiving SMS messages
    
    Content:
    
    - Free plan with access to their SMS API
    - Includes up to 10 messages per month
10. [[Disaster Tracker](https://eonet.gsfc.nasa.gov/api/v3/events)](https://eonet.gsfc.nasa.gov/api/v3/events)
11. Maps JavaScript API: This API allows you to embed interactive maps into your web pages and applications using JavaScript.
12. Places API: The Places API provides programmatic access to location-based data, including details about businesses, points of interest, and geographic locations.
13. Directions API: The Directions API provides routing information between two or more locations. This API allows you to calculate and display driving, walking, or cycling directions on a map.
14. Geocoding API: The Geocoding API allows you to convert street addresses and other location data into geographic coordinates (latitude and longitude), which can then be used to display a marker on a map or to calculate directions.
15. Street View Static API: This API allows you to embed static street view images into your application.
16. Distance Matrix API: The Distance Matrix API allows you to calculate travel distances and times between multiple locations.
17. Elevation API: The Elevation API allows you to retrieve elevation data for any location on the Earth's surface.
18. Time Zone API: The Time Zone API provides time zone data for any location on Earth, based on longitude and latitude coordinates.
