### ISSUE TITLE
Database Connection for Postgres for Python

### ISSUE THREAD

**Issue by mehmetkuzu** [bounswe/bounswe2023group2#172]
### Issue Description

Some of us will be using postgres for data persistence.
This will be my way (At first thought I considered to have common usage but that is not necessary)
I will have a secrets.py file which I will put its name in .gitignore
as:

pgGroup2User = 'dev2022400393'
pgGroup2Pass = 'toBeChanged'
pgGroup2DBName = 'cmpe352db2023'

Next year in our real life implementation we will use THE same database, but for this time we can create a database each.

So during deployment these postgres databases and users will be created on the amazon server also.

### TODO
- Option 1
    - Will send Hasan the database and user names which will be used by own api code
    - He will create them
- Option 2
    - Hasan will provide us ssh connection info to the amazon server and we will do the rest
    
### Deadline of the Issue

11.05.2023

### Reviewer

None

**Comment by cahidenes** [comment]
For ease of use, we can use default database and user, I don't have any idea with the password
