### ISSUE TITLE
Create Research wiki page

### ISSUE THREAD

**Issue by cahidenes** [bounswe/bounswe2023group2#2]
A research wiki page will be created. It will contain the following:
- [x] Links to individual research pages
- [x] Template about how to write individual research pages

Each member will fill in his/her research page.
- [x] [Aras Güngöre](https://github.com/bounswe/bounswe2023group2/wiki/Aras-G%C3%BCng%C3%B6re---Research)
- [x] [Begüm Arslan](https://github.com/bounswe/bounswe2023group2/wiki/Beg%C3%BCm-Arslan---Research)
- [x] [Cahid Enes Keleş](https://github.com/bounswe/bounswe2023group2/wiki/Cahid-Enes-Kele%C5%9F---Research)
- [x] [Egecan Serbester](https://github.com/bounswe/bounswe2023group2/wiki/Egecan-Serbester-Research)
- [x] [Ersel Çanakçılı](https://github.com/bounswe/bounswe2023group2/wiki/Ersel-%C3%87anak%C3%A7%C4%B1l%C4%B1---Research)
- [x] [Halil İbrahim Gürbüz](https://github.com/bounswe/bounswe2023group2/wiki/Halil-%C4%B0brahim-G%C3%BCrb%C3%BCz-Research)
- [x] [Hasan Bingölbali](https://github.com/bounswe/bounswe2023group2/wiki/Hasan-Bing%C3%B6lbali---Research)
- [x] [Mehmet Emin İpekdal](https://github.com/bounswe/bounswe2023group2/wiki/Mehmet-Emin-%C4%B0pekdal---Research)
- [x] [Merve Gürbüz](https://github.com/bounswe/bounswe2023group2/wiki/Merve-G%C3%BCrb%C3%BCz---Research)
- [x] [Ramazan Burak Sarıtaş](https://github.com/bounswe/bounswe2023group2/wiki/Ramazan-Burak-Sar%C4%B1ta%C5%9F---Research)
- [x] [Ömer Şahin Albayram](https://github.com/bounswe/bounswe2023group2/wiki/%C3%96mer-%C5%9Eahin-Albayram---Research)

Deadline: 07.03.2023

**Comment by mervegrbz** [comment]
@cahidenes  Can you add a checkbox for team members [like this](https://github.com/bounswe/bounswe2022group3/issues/5) ? So that we can track the status.

**Comment by bgmrsln** [comment]
@cahidenes You can use [this](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists#creating-task-lists) to create one? Also I created a task list with our names on it we can save these templates on a separate page for reuse.

**Comment by cahidenes** [comment]
> we can save these templates on a separate page for reuse.

Sorry I couldn't get this part.
