### ISSUE TITLE
Create "Requirements" wiki page

### ISSUE THREAD

**Issue by Sahin-Albayram** [bounswe/bounswe2023group2#24]
We need to describe requirements clearly.  I believe that creating a wiki page is best option. 

Revisor: @Sahin-Albayram 
Due to : 14.03.2023 @12.00

**Comment by Sahin-Albayram** [comment]
"https://docs.google.com/document/d/1p43LmFbMPpv-JtXM5wpLioqL-FNB8NVSCLgmA8JGW3w/edit" detailed meeting note.

**Comment by bgmrsln** [comment]
[Requirements in my eyes](https://seemly-politician-629.notion.site/cmpe352-5d431a30d7a743979d7cca868c8f12ed) is the my individual thoughts on some of the requirements

**Comment by bgmrsln** [comment]
Notes on Notion is reviewed and updated by @mervegrbz and @mehmeteminipekdal. I have created the [Informal Requirements](https://github.com/bounswe/bounswe2023group2/wiki/Informal-Requirements) page using them. Any comment and update is welcomed. Also the page is added to Sidebar.

**Comment by bgmrsln** [comment]
Since we will start on working formal requirements now, I am closing this issue. Any new requirement that comes to mind can be added to formal requirements page.
