### ISSUE TITLE
Write a main page for easy redirecting

### ISSUE THREAD

**Issue by mervegrbz** [bounswe/bounswe2023group2#252]
### Issue Description

I think it could be good to add a main page that   the button redirects each work.

### Deadline of the Issue

22.05.2023

### Reviewer

None

**Comment by bgmrsln** [comment]
Can you check this issue @mervegrbz ?

**Comment by mervegrbz** [comment]
I had no time to wap the practice app front end :( Since we have lots of things to do  for the main project. So I am closing the issue
