### ISSUE TITLE
Create personal wiki pages of the new members

### ISSUE THREAD

**Issue by azizamankenova** [bounswe/bounswe2023group2#262]
### Issue Description

Each new group member should create a wiki page, introducing who they are. Check below when the page is completed.

- [x]  [Aziza Mankenova](https://github.com/bounswe/bounswe2023group2/wiki/Aziza-Mankenova)
- [x]  [Buse Tolunay](https://github.com/bounswe/bounswe2023group2/wiki/Buse-Tolunay)
- [x] [Can Bora Uğur](https://github.com/bounswe/bounswe2023group2/wiki/Can-Bora-U%C4%9Fur)

### Deadline of the Issue

17.09.2023

### Reviewer

Merve Gürbüz

**Comment by alper111** [comment]
I have added Aziza and Buse to the team, if that is the issue related to me. Waiting for Can Bora's github username.

**Comment by mehmetkuzu** [comment]
Yes. That was what I understood about your comment in the class. I added you on issues which will be assigned to newcomers. So that you would be reminded to add them to github, and we would assign them instead of you.

**Comment by canbora** [comment]
I have done my part.

**Comment by azizamankenova** [comment]
My personal page is created and can be accessed [here](https://github.com/bounswe/bounswe2023group2/wiki/Aziza-Mankenova).

**Comment by busetolunay** [comment]
I have created my personal wiki page.
