### ISSUE TITLE
Re-verify the Requirements

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#264]
### Issue Description

Members should re-verify the requirements based on the progression made on the project as a team.

### Deadline of the Issue

07.10.2023

### Reviewer

Begüm Arslan

**Comment by mehmetkuzu** [comment]
1. I think all are ok in general. It is not 100 percent assured that nothing will be added or taken out during the next steps, but any way will be exceptional.
2. My only proposition about the current requirements document: The [guest user actions ](https://github.com/bounswe/bounswe2023group2/wiki/Requirements#1131-guest-user-actions) should be a little more limited. Not crucial though. (This, we can make our final decision at the end.)

So: I think it's ok to check the requirements document as verified.

**Comment by egecans** [comment]
Last semester, when I asked Alper Hoca which criteria were bad on our requirements page he asked me as user actions should be under the glossary instead of functional requirements. If I remember his proposal correctly, we can move these user actions to the glossary.

**Comment by mehmetkuzu** [comment]
I could not get the idea here. User Actions part is good as it is located now. Glossary is not appropriate, I think.

**Comment by mervegrbz** [comment]
In previous issue we found inconsistencies  in the user requirements. I am closing the issue since we did not find any other
