### ISSUE TITLE
Update the Class Diagrams with respect to the changes in the requirements

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#265]
### Issue Description

Class Diagrams must be updated based on the changes made in the requirements during #264.

### Deadline of the Issue

07.10.2023

### Reviewer

Egecan Serbester

**Comment by bgmrsln** [comment]
Parts that are irrelated should be deleted: 
<img width="142" alt="image" src="https://github.com/bounswe/bounswe2023group2/assets/53114791/35f36d34-f2ca-439a-be20-480563563846">

**Comment by egecans** [comment]
It seems okay after correcting some small typos. You can view the latest class diagram from this [link](https://lucid.app/lucidchart/12dfcb9b-df14-4b9f-a228-58b117165a21/edit?viewport_loc=-2376%2C-3246%2C6135%2C2799%2C8g-MqJXAl9Ll&invitationId=inv_8a88f82c-9cd0-46dc-a8e0-b570787cd833)
Thanks for your efforts. I will also update our class diagram on the wiki
