### ISSUE TITLE
Update the Use Case Diagrams with respect to the changes in the requirements

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#266]
### Issue Description

Use Case Diagrams must be updated based on the changes made in the requirements during #264.

### Deadline of the Issue

10.10.2023

### Reviewer

None

**Comment by rburaksaritas** [comment]
Fixed some typos and flaws, here is the current chart link:
https://lucid.app/lucidchart/4155dbe6-5f07-4815-8a5c-24824b2430eb/edit?viewport_loc=-5970%2C2017%2C10404%2C5993%2C0_0&invitationId=inv_02382a02-762b-4f57-b82d-1f06b005f688

@canbora

**Comment by canbora** [comment]
I have reorganized the notifications section and fixed a typo.
