### ISSUE TITLE
Update the Sequence Diagrams with respect to the changes in the requirements

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#267]
### Issue Description

Sequence Diagrams must be updated based on the changes made in the requirements during #264.

### Deadline of the Issue

10.10.2023

### Reviewer

None

**Comment by mehmetkuzu** [comment]
Do you thing it's ok to change the deadline of "update diagram" issues to monday. (October 9th)?

**Comment by cahidenes** [comment]
Changes:
- Migrated to a new chart:  [link](https://lucid.app/lucidchart/e6e5be33-d230-4427-8ac7-fd4b1b8e8eb2/edit?viewport_loc=-1553%2C-7794%2C4807%2C2441%2C0_0&invitationId=inv_fc278e76-e868-4582-84dc-c201e2087b57)
- Added "role" to authenticated user profile information.
- Added "Role-based User" next to all "Authenticated User"s
- Added a new chart related to requirement 1.1.3.3.2: Role-based users shall be able to search for activities that are related to their proficiency.
- Added new case to edit profile for role-based users
- Texts of creating activities are changed to include requirement 1.2.3.5: Locations which were previously added should be able to be selected when creating an activity.
