### ISSUE TITLE
Deciding on communication tools

### ISSUE THREAD

**Issue by halil-gurbuz** [bounswe/bounswe2023group2#268]
### Issue Description

The team should create communication plan and decide which communication tools to use. (Whatsapp, Discord etc)

### Deadline of the Issue

08.09.2023

### Reviewer

Cahid Enes Keleş

**Comment by mervegrbz** [comment]
I have added the communication plan on wiki. Can you check? @cahidenes @halil-gurbuz

**Comment by halil-gurbuz** [comment]
I reviewed it. Good work, thanks. I am closing this issue.
