### ISSUE TITLE
Select a sub-team

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#269]
### Issue Description

Each member must decide on their sub-teams: front-end, back-end or mobile.

### Deadline of the Issue

10.10.2023

### Reviewer

Halil İbrahim Gürbüz

**Comment by mehmetkuzu** [comment]
How will we proceed with this?
I propose:
All members comment here about their intentions and one of us check the balance of groups and announce (propose) the subgroups.
(This member may be Merve)

**Comment by mehmetkuzu** [comment]
My intention:
I would rather be a part of the back-end group.
Front-end might be a second choice. But I really do not prefer mobile.
I propose: if back-end group gets too crowded, we can assign some house keeping tasks to this group as well.

**Comment by bgmrsln** [comment]
I thought of sending a google form for everyone to decide on their groups. I think we should split as 4-4-4 or 5-4-3. I also considered possibility of Şahin joining us back.   Other case can be as 4-4-3, and 5-3-3.

**Comment by halil-gurbuz** [comment]
> I thought of sending a google form for everyone to decide on their groups. I think we should split as 4-4-4 or 5-4-3. I also considered possibility of Şahin joining us back. Other case can be as 4-4-3, and 5-3-3.

1st choice and 2nd choice may be asked in the form.

**Comment by mehmetkuzu** [comment]
How about having a table with:
rows as members
columns as 1st choice, second choice, 3rd choice

**Comment by mehmetkuzu** [comment]
| Member            |  1  |  2  |. 3. |
|-----------------|:-------------:|------:|------:|
| Mehmet K. |  B  |  F  |  M  |

**Comment by halil-gurbuz** [comment]
> How about having a table with: rows as members columns as 1st choice, second choice, 3rd choice

3rd is obvious, I think first and second enough for compact table.

**Comment by mehmetkuzu** [comment]
If its ok, we can add a page for this? So that every one of us edits his/her line.

**Comment by halil-gurbuz** [comment]
> If its ok, we can add a page for this? So that every one of us edits his/her line.

We can edit your comment :)

**Comment by mehmetkuzu** [comment]
For the sake of clearity: We are doing this with Google Forms. Link is: https://docs.google.com/forms/d/e/1FAIpQLSfj-SuBIlO50Ll2JCwVirm3G2-khyj4P82uauFpnysUJi3q8w/viewform?usp=sf_link

**Comment by mervegrbz** [comment]
@bgmrsln @mehmetkuzu can you also add the results of the form. So that we can  know the sub-team members

**Comment by bgmrsln** [comment]
<img width="767" alt="image" src="https://github.com/bounswe/bounswe2023group2/assets/53114791/22878d93-d9b7-43c9-a30c-e0756792b8bc">

**Comment by mervegrbz** [comment]
Frontend: Can bora, Merve, (Sahin)
Mobile: Egecan, Halil, Hasan, Cahid
Backend:  Begum, Buse, Aziza, Mehmet, Burak
Devops- CI/CD: Merve, Begum, Mehmet

The results are listed below.

**Comment by halil-gurbuz** [comment]
> Frontend: Can bora, Merve, (Sahin) Mobile: Egecan, Halil, Hasan, Cahid Backend: Begum, Buse, Aziza, Mehmet, Burak Devops- CI/CD: Merve, Begum, Mehmet
> 
> The results are listed below.

Done, I'm closing.
