### ISSUE TITLE
Decide on a tool for mockups

### ISSUE THREAD

**Issue by mehmetkuzu** [bounswe/bounswe2023group2#27]
### Issue Description

For validation we will need to provide the Project Owner with mockups.
No need to be perfectionist, actually any tool will do.
The only "requirement" about this tool (as I think) is:
- The design spec should be available to be stored in github. (So that we can easily cowork on it. And version using github features)
- XML output is _preferrable_
-  Simplicity is a plus

### Deadline of the Issue

18.03.2023

### Reviewer

None

**Comment by mehmetkuzu** [comment]
Assigned myself for a start. Not all of us but some of us can work on this.

**Comment by mehmetkuzu** [comment]
This might not be the best, but it seems to me it's more than enough.
In the assignment 1 of CMPE321, diagrams.net was mentioned.

1. It is an Online tool (+)
2. Github repositories are used for storing and version control (+)
3. XML format (+) 
4. Will be usefull for future needs. (Any task. ER Diagrams etc) (+)

**Comment by mehmetkuzu** [comment]
Just to give an idea. This is a screenshot
<img width="1418" alt="SSFordiagramnetMockup" src="https://user-images.githubusercontent.com/46297916/225833764-06d1e930-e6da-4156-930c-45098e16979b.png">

**Comment by bgmrsln** [comment]
I think it is very useful. I will be using it to create a mock up for [account features](https://github.com/bounswe/bounswe2023group2/wiki/SRS-Document-for-Disaster-Response-and-Recovery-%5BDraft%5D#23-account-features)

**Comment by mehmetkuzu** [comment]
Right.
So it's a good idea to use mockups in the SRS.
(But if it's ok for the group as a whole. Otherwise one of the main criteria will be violated - consistency)

**Comment by mehmetkuzu** [comment]
diagrams.net
