### ISSUE TITLE
Decide on what technologies are going to be used for the Back-end development

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#271]
### Issue Description

Back-end team must decide on the technologies to be used during the project development.

- [ ] Coding
- [ ] API infrastucture
- [ ] Database connectivity
- [ ] Session management (Login status etc.)
- [ ] ...

### Deadline of the Issue

10.10.2023

### Reviewer

None

**Comment by mehmetkuzu** [comment]
I added the sub-decisions. Other points may be added too.

**Coding**
Python - with virtual environment

**API Structure:**
FastAPI. 

**Database connectivity**
MongoDB chosen so python connector for MongoDB

**Session management**
I am not so familiar with this but I feel that some mechanisms (like tokens etc) serving the purpose should be found.

**Comment by rburaksaritas** [comment]
Definitely not PostgreSQL for database IMO, since it hurted our brains last year in the practice-app.

**Comment by mervegrbz** [comment]
> I added the sub-decisions. Other points may be added too.
> 
> **Coding** Python - with virtual environment
> 
> **API Structure:** FastAPI.
> 
> **Database connectivity** MongoDB chosen so python connector for MongoDB
> 
> **Session management** I am not so familiar with this but I feel that some mechanisms (like tokens etc) serving the purpose should be found.

What do you mean by Session Management? I could not understand the concept :*

**Comment by mehmetkuzu** [comment]
> > I added the sub-decisions. Other points may be added too.
> > **Coding** Python - with virtual environment
> > **API Structure:** FastAPI.
> > **Database connectivity** MongoDB chosen so python connector for MongoDB
> > **Session management** I am not so familiar with this but I feel that some mechanisms (like tokens etc) serving the purpose should be found.
> 
> What do you mean by Session Management? I could not understand the concept :*

Managing the user logins and API calls.
