### ISSUE TITLE
Edit & Update the Sidebar of Wiki 

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#273]
### Issue Description

Sidebar of our wiki page must be edited and updated to add CMPE451

### Deadline of the Issue

07.10.2023

### Reviewer

None

**Comment by rburaksaritas** [comment]
Updated the team members section.

**Comment by mehmetkuzu** [comment]
Can we write Şahin back there. I guess in the end his e-petiton will be accepted and he will continue with us.
(Also his name may be put back to members - instead of former members)

**Comment by mehmetkuzu** [comment]
Closing issue. We can add Şahin after he rejoins the group/course.
