### ISSUE TITLE
Edit & Update the README page of Repository

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#275]
### Issue Description

README page of our code repository must be edited and updated to add CMPE451 and new team members.

### Deadline of the Issue

07.10.2023

### Reviewer

None

**Comment by mehmetkuzu** [comment]
I reviewed and merged the README.md but Can Bora and Buse should prepare their own personal pages. (Provide links to these.) And we will update the links.

**Comment by mehmetkuzu** [comment]
Closing this issue. README page is ok now. The link for Buse will become useful as Buse publishes her personal page.
