### ISSUE TITLE
CI/CD - Prepare a CI/CD pipeline

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#284]
### Issue Description

To automate the software delivery process and ensure seamless code integration,  a simple robust CI/CD backbone is planned to be built. This draft will outline the primary requirements and dependencies of the development process. 

### Deadline of the Issue

17.10.2023

### Reviewer

Mehmet Kuzulugil

**Comment by mervegrbz** [comment]
I have deployed the app to the EC2 I will do the deployment manually for a while, since the development is in its early steps
