### ISSUE TITLE
CI/CD - Prepare a Wiki document about the usage & local implementation of docker

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#285]
### Issue Description

To guide team members and newcomers on how to use and implement our CI/CD system locally, a comprehensive Wiki document is proposed. This document will highlight key steps, best practices, and troubleshooting tips for a smooth CI/CD experience.

### Deadline of the Issue

17.10.2023

### Reviewer

Begüm Arslan

**Comment by mervegrbz** [comment]
I think there is a misunderstanding about CI/CD and containerization. I have written how to use docker local and CI/CD will help us deploy our application on the server automatically.  You can see the tutorial [here](https://github.com/bounswe/bounswe2023group2/wiki/Docker-and-local-deployment-tutorial)
