### ISSUE TITLE
Frontend - Self-training of decided technologies

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#287]
### Issue Description

To ensure our web interfaces' success, Front-end team members should do a self-training on our chosen front-end technologies (Next.js). This effort is to familiarize the team with the latest practices and design paradigms.

- [x] Merve
- [x] Can Bora
- [x] Şahin (if he can make it to the CMPE451)

### Deadline of the Issue

17.10.2023

### Reviewer

Merve Gürbüz

**Comment by mervegrbz** [comment]
Sahin added to the project, We worked on Next. js documentation and Udemy course.
