### ISSUE TITLE
Mobile - Self-training of decided technologies

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#288]
### Issue Description

Self-training on our determined mobile technologies is encouraged. This self-learning drive ensures our mobile applications are efficient, user-friendly, and in line with project requirements.

- [x] Egecan
- [x] Cahid Enes
- [x] Hasan
- [x] Halil İbrahim

### Deadline of the Issue

17.10.2023

### Reviewer

Cahid Enes Keleş

**Comment by egecans** [comment]
If you are a newbie, I strongly recommend this [video series](https://www.youtube.com/playlist?list=PLQkwcJG4YTCTq1raTb5iMuxnEB06J1VHX). I learned most of the things from there. 
You can also watch [this](https://www.youtube.com/playlist?list=PLQkwcJG4YTCT0RouHZ6sQlE4JE6VyD2zO) to learn MVVM concepts basically, that was my first course. I love this channel for Android, you can also glance at his other videos.

**Comment by halil-gurbuz** [comment]
> If you are a newbie, I strongly recommend this [video series](https://www.youtube.com/playlist?list=PLQkwcJG4YTCTq1raTb5iMuxnEB06J1VHX). I learned most of the things from there. You can also watch [this](https://www.youtube.com/playlist?list=PLQkwcJG4YTCT0RouHZ6sQlE4JE6VyD2zO) to learn MVVM concepts basically, that was my first course. I love this channel for Android, you can also glance at his other videos.

I watched some videos from the first video series last week. I will continue watching next week.

**Comment by HasanBingolbali** [comment]
I trained myself on Generic Types, adding dependencies, managing state flow and UI creation using xml

**Comment by cahidenes** [comment]
I was able to learn some basic Kotlin with examining written code by other team members.
