### ISSUE TITLE
Setting Meeting Rules

### ISSUE THREAD

**Issue by mervegrbz** [bounswe/bounswe2023group2#29]
### Issue Description

We have a template for meetings, but I think we need to describe how we can utilize our meeting template with defining a guideline.

### Deadline of the Issue

17.03.2023

### Reviewer

Begüm Arslan

**Comment by mervegrbz** [comment]
@bgmrsln can you check the page? I have added some rules and description for better meeting experience :)

**Comment by bgmrsln** [comment]
It seem to be good. We can revise it if need arise.
