### ISSUE TITLE
Mobile - Navigation route page structure

### ISSUE THREAD

**Issue by halil-gurbuz** [bounswe/bounswe2023group2#291]
### Issue Description

Navigation structure will be created

### Deadline of the Issue

17.10.2023

### Reviewer

Cahid Enes Keleş

**Comment by egecans** [comment]
Required pages can be sorted as:

Registration Page,
Login Page,
Forgot Password Page,
Change Password Page,

Guest's Home Page:
Map Page

Authenticated / Role-Based User Home Page:
Add & Update Resource,
Add & Update Need,
Add & Update Action,
Add & Update Event,
List Resources Pages
List Need
List Action
List Event

Profile:
User Activities
Notifications

Admin Panel:
Reports Page

**Comment by egecans** [comment]
I added the home page and then added
Authentication Pages (Login, Registration, Forgot and Change Password)
I added buttons on those pages for navigating corresponding pages.
After that, I added Profile, Map, Activity page and Emergency with adding Emergency page in Activity Pages.
I created a proper package design, you can follow my guide while creating new Fragments.
I also documented my functions for better understanding.  You can fill in the remaining pages because basic UI implementation is similar to what I did. In this way, you will develop yourselves in Android UI design which will be needed the whole semester.

**Comment by egecans** [comment]
@halil-gurbuz  Can you fill Action and Event under the activity page? You should do that by creating new Fragments as I did in the Emergency Page. Then you should also navigate corresponding activities into add activity fragments. i.e. in Event Fragment, you should have dummy text (Event Page) and a button that navigates to add Event Fragment. 

@cahidenes  Can you fill Need and Resource under the activity page? You should follow the same steps with @halil-gurbuz 

@HasanBingolbali  Can you fill Profile Page? You should create UserActivitiesFragment with a dummy layout. Then create a Subscribe Notification Fragment with a dummy UI and a button for navigating Add Notification which has a dummy layout as I did in Authenticated-Related Pages.

**Comment by egecans** [comment]
You can watch these videos [Layout Basics](https://www.youtube.com/watch?v=yx3xzuNCJKc&list=PLQkwcJG4YTCTq1raTb5iMuxnEB06J1VHX&index=5), [Constraint Layout Basics](https://www.youtube.com/watch?v=VsgXFdynDuQ&list=PLQkwcJG4YTCTq1raTb5iMuxnEB06J1VHX&index=7), 
[Fragments Basics](https://www.youtube.com/watch?v=-vAI7RSPxOA&list=PLQkwcJG4YTCTq1raTb5iMuxnEB06J1VHX&index=22)
You can also watch other videos for [Android Fundamentals](https://www.youtube.com/playlist?list=PLQkwcJG4YTCTq1raTb5iMuxnEB06J1VHX) I strongly recommend this channel again!

**Comment by halil-gurbuz** [comment]
> @halil-gurbuz Can you fill Action and Event under the activity page? You should do that by creating new Fragments as I did in the Emergency Page. Then you should also navigate corresponding activities into add activity fragments. i.e. in Event Fragment, you should have dummy text (Event Page) and a button that navigates to add Event Fragment.
> 
> @cahidenes Can you fill Need and Resource under the activity page? You should follow the same steps with @halil-gurbuz
> 
> @HasanBingolbali Can you fill Profile Page? You should create UserActivitiesFragment with a dummy layout. Then create a Subscribe Notification Fragment with a dummy UI and a button for navigating Add Notification which has a dummy layout as I did in Authenticated-Related Pages.

I added **Action List** and **Add Action** pages. I will add **Event** pages soon.

**Comment by halil-gurbuz** [comment]
I added Need, Action, Event and Resource pages.

**Comment by egecans** [comment]
I added the remaining pages since #350 merged, I closed the issue good job!
