### ISSUE TITLE
Initial Database - Installation and Design Setup

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#292]
### Issue Description

To initialize our application's data management, we must initialize the installation and design setup of our primary database. This involves crafting an initial schema with MongoDB that aligns with our application's requirements. This foundational step ensures our data is structured, accessible and scalable.

### Deadline of the Issue

17.10.2023

### Reviewer

None

**Comment by azizamankenova** [comment]
Looking into it [here](https://www.mongodb.com/developer/languages/python/python-quickstart-fastapi/). 
It explains how to get started with MongoDB and FastAPI. 
I'm following the steps however, I am getting a few errors. Trying to solve them.

**Comment by mervegrbz** [comment]
I have added dockerfile and docker-compose files for Mongo and a tutorial on the wiki page for Mongo db usage local.  We tried to solve the problem that happened in @azizamankenova's computer but not go well. We will use the connection we built on practice-app the previous semester. The backend team is working on it. For the first milestone, we achieved our goal
