### ISSUE TITLE
Mobile - Create Network Utility Class

### ISSUE THREAD

**Issue by HasanBingolbali** [bounswe/bounswe2023group2#293]
### Issue Description

Create network utility class in Kotlin. It must support request-type, endpoint url, headers and request body

### Deadline of the Issue

17.10.2023

### Reviewer

Egecan Serbester

**Comment by HasanBingolbali** [comment]
I created PR: #319. Needs approval for merge

**Comment by egecans** [comment]
with #320 it is closed. Good job!
