### ISSUE TITLE
Arrange Utility Mailbox for the Project (with boun.edu.tr extension)

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#295]
### Issue Description

Utility mailbox for the project will be arranged with boun.edu.tr extension. With SMTP configuration tested.

### Deadline of the Issue

17.10.2023

### Reviewer

Halil İbrahim Gürbüz

**Comment by mehmetkuzu** [comment]
I talked with Ms. Üsküdarlı about that. Seems this is not possible under current circumstances.
That means we will use other providers within their limits.
