### ISSUE TITLE
Mobile - Authentication related page initialization

### ISSUE THREAD

**Issue by halil-gurbuz** [bounswe/bounswe2023group2#296]
### Issue Description

The login page, Signup page, Forgot Password, and Change Password pages will be filled.
These pages will not function initially, only for visuals.

### Deadline of the Issue

24.10.2023

### Reviewer

Egecan Serbester

**Comment by cahidenes** [comment]
Related commits: [this](https://github.com/bounswe/bounswe2023group2/commit/3dc18a1d5a41fd6bb489ec3dd2298cadee72174c) and [this](https://github.com/bounswe/bounswe2023group2/commit/ccb23a777a6b3cc1c226f8e9efd9b875e4c9fb5a)

**Comment by egecans** [comment]
It can be closed since it was merged.
