### ISSUE TITLE
Project Plan Contribution: Back-end Perspective

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#297]
### Issue Description

Back-end team's contribution is required for the project plan. They must specify their tasks that will be done until the Milesones.

### Deadline of the Issue

19.10.2023

### Reviewer

Begüm Arslan

**Comment by mehmetkuzu** [comment]
Discussion #303 for this.
- Let's try to be definitive. Instead of free discussion, I preferred to write parts which can be transferred -after discussing and reviewing- to a project plan document.
- Let's reply the points of discussion in seperate.

**Comment by bgmrsln** [comment]
We have done the backend part with the helps of @mehmetkuzu , @bgmrsln , @azizamankenova .
