### ISSUE TITLE
Project Plan Contribution: Front-end Perspective

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#298]
### Issue Description

Front-end team's contribution is required for the project plan. They must specify their tasks that will be done until the Milesones.

### Deadline of the Issue

19.10.2023

### Reviewer

Merve Gürbüz

**Comment by mehmetkuzu** [comment]
A common project plan element: Milestone 1.
A comment in [back-end discussion](https://github.com/bounswe/bounswe2023group2/discussions/303#discussioncomment-7250792) exists. I think it will interest other subteams too.

**Comment by mervegrbz** [comment]
We have done the planning part since verify it with @canbora
