### ISSUE TITLE
Project Plan Contribution: Mobile Perspective

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#299]
### Issue Description

Mobile team's contribution is required for the project plan. They must specify their tasks that will be done until the Milesones.

### Deadline of the Issue

19.10.2023

### Reviewer

Cahid Enes Keleş

**Comment by mehmetkuzu** [comment]
A common project plan element: Milestone 1.
A comment in [back-end discussion](https://github.com/bounswe/bounswe2023group2/discussions/303#discussioncomment-7250792) exists. I think it will interest other subteams too.

**Comment by egecans** [comment]
I created deliverables on Project Plan for Mobile, I arranged due times and assignees. Is it ok?

**Comment by egecans** [comment]
> I created deliverables on Project Plan for Mobile, and I arranged due times and assignees. Could you check if is that ok?

**Comment by halil-gurbuz** [comment]
> I created deliverables on Project Plan for Mobile, and I arranged due times and assignees. Could you check if is that ok?

I checked, It is comprehensive and well organized.

**Comment by egecans** [comment]
> > I created deliverables on Project Plan for Mobile, and I arranged due times and assignees. Could you check if is that ok?
> 
> I checked, It is comprehensive and well organized.

Okay, thanks for your review, I close the issue then.
