### ISSUE TITLE
Editing Wiki Sidebar 

### ISSUE THREAD

**Issue by mervegrbz** [bounswe/bounswe2023group2#3]
Wiki sidebar needs to be organized for convenience. Headers needed are : Team Members, Weekly Meetings, Research

Due Date: 07.03.2023 - Tuesday
Revisor: @mervegrbz

**Comment by mervegrbz** [comment]
You can add your header ideas in comments.

**Comment by cahidenes** [comment]
I have already included the "Who we are" page and the "Research" page in the "Etc" header before reading this issue. Should they be separate?

**Comment by mervegrbz** [comment]
> I have already included the "Who we are" page and the "Research" page in the "Etc" header before reading this issue. Should they be separate?

Hi, I think the header should give us a inderstanding of what is in the pages linked under that header, Etc may not help :/

**Comment by halilgurbuz** [comment]
Some personal pages are not linked on the sidebar and wiki page. I fixed them.

**Comment by mervegrbz** [comment]
I have added issue and meeting template under rule and management. Closing the issue.
