### ISSUE TITLE
Adding new members to course

### ISSUE THREAD

**Issue by Sahin-Albayram** [bounswe/bounswe2023group2#308]
### Issue Description

Somebody says king is dead then everyone should know the legend came back.  Since my e-petition passed faculty step and it is in registiration office now, hopefully, I will re-join this course soon.

### Deadline of the Issue

30.10.2023

### Reviewer

None

**Comment by halil-gurbuz** [comment]
Welcome back King

**Comment by mervegrbz** [comment]
Hi @alper111 can you add @Sahin-Albayram to the group? Thank you in advance 🚀

**Comment by alper111** [comment]
🫡
