### ISSUE TITLE
Defining branch name rules

### ISSUE THREAD

**Issue by mervegrbz** [bounswe/bounswe2023group2#310]
### Issue Description

It is good practice to create branches with a good title that explains what it is about. Moreover writing branch names in the same naming convention will help others to contribute to the project (camelcase, snake ...).  Lastly classifying the branches with their types (bugfix, feature ...). 

So we should create a wiki page to define our repository rules.

### Deadline of the Issue

15.10.2023

### Reviewer

Egecan Serbester

**Comment by bgmrsln** [comment]
@egecans Can you review the page: https://github.com/bounswe/bounswe2023group2/wiki/Branch-Name-Rules

**Comment by bgmrsln** [comment]
Should we include the author name on the branch like bgmrsln/BE/feature/login-endpoints?

**Comment by Sahin-Albayram** [comment]
> Should we include the author name on the branch like bgmrsln/BE/feature/login-endpoints?

I think it makes sense, but I'm stuck on one point. Shouldn't changing the order be more modular? like make team first "BE/bgmrsln/feature/login-endpoints?"

**Comment by mehmetkuzu** [comment]
> > Should we include the author name on the branch like bgmrsln/BE/feature/login-endpoints?
> 
> I think it makes sense, but I'm stuck on one point. Shouldn't changing the order be more modular? like make team first "BE/bgmrsln/feature/login-endpoints?"

I think member name is important. Because we need to know "whose branch is that, who is working on this".
Not sure about the "team name" though.

Actually best way would be include the "**subtype**" name of the related effort instead of the team of the member. (It won't be a common practice but sometimes we may have a branch by a frontend member who actually changing a backend code part)
subtype is still BE, FE, MO

My examples would be:

begmrsln/BE/feature/login-endpoints

sahin-albayram/FE/feature/login-ui

sahin-albayram/BE/hotfix/login-endpoints

**Comment by Sahin-Albayram** [comment]
> > > Should we include the author name on the branch like bgmrsln/BE/feature/login-endpoints?
> > 
> > 
> > I think it makes sense, but I'm stuck on one point. Shouldn't changing the order be more modular? like make team first "BE/bgmrsln/feature/login-endpoints?"
> 
> I think member name is important. Because we need to know "whose branch is that, who is working on this". Not sure about the "team name" though.
> 
> Actually best way would be include the "**subtype**" name of the related effort instead of the team of the member. (It won't be a common practice but sometimes we may have a branch by a frontend member who actually changing a backend code part) subtype is still BE, FE, MO
> 
> My examples would be:
> 
> begmrsln/BE/feature/login-endpoints
> 
> sahin-albayram/FE/feature/login-ui
> 
> sahin-albayram/BE/hotfix/login-endpoints

Ok then, that convinced me

**Comment by bgmrsln** [comment]
In the software projects I've encountered, the author's name isn't typically included in branch names. Additionally, for certain branches, we might work together as assigned in the project plan. Therefore, it might be more practical to omit the author's name from branch names.

**Comment by mehmetkuzu** [comment]
> In the software projects I've encountered, the author's name isn't typically included in branch names. Additionally, for certain branches, we might work together as assigned in the project plan. Therefore, it might be more practical to omit the author's name from branch names.

This might be more professional but for our needs we should have the option to include the name.

So how about

/BE/feature/login-endpoints_bybgmrsln
/BE/feature/login-endpoints_bybgmrsln_sahin
/BE/feature/login-endpoints_enhancingForgotPass

We can use all of them (depending...)
And again BE, MO and FE shows the section not the subteam.

**Comment by egecans** [comment]
> @egecans Can you review the page: https://github.com/bounswe/bounswe2023group2/wiki/Branch-Name-Rules

It seems so good, thank you! But I don't understand why [this link](https://medium.com/@ketansomvanshi007/structuring-a-fastapi-app-an-in-depth-guide-cdec3b8f4710) is at the bottom of the page. Was it put there unintentionally, or did it have a purpose?

**Comment by egecans** [comment]
> > In the software projects I've encountered, the author's name isn't typically included in branch names. Additionally, for certain branches, we might work together as assigned in the project plan. Therefore, it might be more practical to omit the author's name from branch names.
> 
> This might be more professional but for our needs we should have the option to include the name.
> 
> So how about
> 
> /BE/feature/login-endpoints_bybgmrsln /BE/feature/login-endpoints_bybgmrsln_sahin /BE/feature/login-endpoints_enhancingForgotPass
> 
> We can use all of them (depending...) And again BE, MO and FE shows the section not the subteam.

I think that's not necessary. As Begüm said, the important thing will be features and types, not the ones that created branches. So, I think branch names like BE/feature/login-endpoints is OK. Moreover, If you really wonder about who created or updated the branch, you can check them under the branch name.

**Comment by mehmetkuzu** [comment]
> > > In the software projects I've encountered, the author's name isn't typically included in branch names. Additionally, for certain branches, we might work together as assigned in the project plan. Therefore, it might be more practical to omit the author's name from branch names.
> > 
> > 
> > This might be more professional but for our needs we should have the option to include the name.
> > So how about
> > /BE/feature/login-endpoints_bybgmrsln /BE/feature/login-endpoints_bybgmrsln_sahin /BE/feature/login-endpoints_enhancingForgotPass
> > We can use all of them (depending...) And again BE, MO and FE shows the section not the subteam.
> 
> I think that's not necessary. As Begüm said, the important thing will be features and types, not the ones that created branches. So, I think branch names like BE/feature/login-endpoints is OK. Moreover, If you really wonder about who created or updated the branch, you can check them under the branch name.

OK. Convinced.
Now we should add a small document to our wiki.
Like Branch naming rules. (Later we can merge the rules documents -about git code repository usage- into one. If there happens to exist others)
@bgmrsln ?

**Comment by mehmetkuzu** [comment]
The document should be updated so that we use the section name not the team name we are a part of.

**Comment by bgmrsln** [comment]
> > @egecans Can you review the page: https://github.com/bounswe/bounswe2023group2/wiki/Branch-Name-Rules
> 
> It seems so good, thank you! But I don't understand why [this link](https://medium.com/@ketansomvanshi007/structuring-a-fastapi-app-an-in-depth-guide-cdec3b8f4710) is at the bottom of the page. Was it put there unintentionally, or did it have a purpose?

It was a link for another issue, sorry for the misput. Since we have agreed I am closing the issue
