### ISSUE TITLE
Add Branch Name Rules into SideBar

### ISSUE THREAD

**Issue by egecans** [bounswe/bounswe2023group2#318]
### Issue Description

[Branch Name Rules page](https://github.com/bounswe/bounswe2023group2/wiki/Branch-Name-Rules) is very instructive for us. Therefore, this page should be added to the wiki sidebar for easy access.

### Deadline of the Issue

17.10.2023

### Reviewer

Begüm Arslan

**Comment by egecans** [comment]
I added rules section under CMPE451 from CMPE352. I also added branch name rules in this section. Can you review it @bgmrsln ?

**Comment by halil-gurbuz** [comment]
Maybe we can move CMPE451 section to above the CMPE352 section in the sidebar. I think it will be much useful.

**Comment by egecans** [comment]
> Maybe we can move CMPE451 section to above the CMPE352 section in the sidebar. I think it will be much useful.

A good point, I moved it.

**Comment by bgmrsln** [comment]
I think this page can also be added to sidebar: https://github.com/bounswe/bounswe2023group2/wiki/API-conventions

**Comment by bgmrsln** [comment]
It is added, closing the issue <3
