### ISSUE TITLE
Backend - Profile edit-create-delete endpoint implementation

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#324]
### Description
Backend CRUD endpoints for Profile must be implemented:

- [ ] POST: Creating user profiles.
- [ ] GET: Reading user profile.
- [ ] PUT: Updating existing profile details.
- [ ] DELETE: Deleting user profiles.

Ensure endpoints have validation and return appropriate status codes as stated in the [API convention document](https://github.com/bounswe/bounswe2023group2/wiki/API-conventions).

### Deadline
26.10.2023

**Comment by mehmetkuzu** [comment]
CRUD for Optional user infos is ready. After a review of this part, other subclasses of user profile will be written accordingly.

**Comment by mehmetkuzu** [comment]
Some parts are finished as a start last week. 
New issues for improvements were opened. So closing this issue.
