### ISSUE TITLE
Backend - Resource CRUD endpoint implementation

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#325]
### Description
Backend CRUD endpoints for Resource must be implemented:

- [x] POST: Creating resource.
- [x] GET: Reading resource.
- [x] PUT: Updating resource.
- [x] DELETE: Deleting resource.

Ensure endpoints have validation and return appropriate status codes as stated in the [API convention document](https://github.com/bounswe/bounswe2023group2/wiki/API-conventions).

### Deadline
25.10.2023

**Comment by rburaksaritas** [comment]
CRUD endpoints for resources, along with the resource_model are implemented on #363.

**Comment by busetolunay** [comment]
`initialQuantity: int = Field(default=None)
    unsuppliedQuantity: int = Field(default=None)`
    We defined the initialQuantitiy and currentQuantitiy fields in the class diagram of resource. Does unsupplied quantity corresponds to the currentQuantity or is there a typo in the code ?

**Comment by rburaksaritas** [comment]
@busetolunay yes, i confused Resource with Need i guess. :) Let me fix that, thanks.

**Comment by rburaksaritas** [comment]
> `initialQuantity: int = Field(default=None) unsuppliedQuantity: int = Field(default=None)`
> We defined the initialQuantitiy and currentQuantitiy fields in the class diagram of resource. Does unsupplied quantity corresponds to the currentQuantity or is there a typo in the code ?

fixed, please ```git pull origin BE/feature/resource``` for the changes.
