### ISSUE TITLE
Backend - Authentication related endpoint implementation

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#327]
### Description
Backend endpoints for Authentication must be implemented:
- [x] #367
- [x] #368
- [x] Backend - Login
- [x] #376

Ensure endpoints have validation and return appropriate status codes as stated in the [API convention document](https://github.com/bounswe/bounswe2023group2/wiki/API-conventions).

### Deadline
25.10.2023

**Comment by bgmrsln** [comment]
Since signup problems are fixed, closing the issue
