### ISSUE TITLE
Mobile - Profile page UI

### ISSUE THREAD

**Issue by cahidenes** [bounswe/bounswe2023group2#335]
### Issue Description

The profile page of the mobile application should be implemented. This page also contains data binding. When the user fills the form, posted parameters should be logged successfully.

### Deadline of the Issue

21.10.2023

### Reviewer

Hasan Bingölbali

**Comment by cahidenes** [comment]
This issue is resolved with #375

**Comment by halil-gurbuz** [comment]
Since this feature branch is merged with main, I closed this issue.
