### ISSUE TITLE
Mobile - Creating local database for offline records

### ISSUE THREAD

**Issue by egecans** [bounswe/bounswe2023group2#339]
We should create a local database for recording user actions in offline mode. We will use Room Database for that, we should also do this code architecture in the scope of MVVM. Therefore, we will create an Entity, DAO (Data Access Object), Repository and ViewModel for all tables we will have. 
Sub-issues for that are:
- [x] #340 
- [x] #341 
- [x] #342 
- [x] #343 
- [x] #344 
- [x] #345

**Comment by egecans** [comment]
I finished Need Table

**Comment by halil-gurbuz** [comment]
> I finished Need Table You can follow my guide: a local database, a Need table, a repository example, a ViewModel example and a dependency Injection example were implemented under this branch. I also added required gradle dependencies

I finished ActionTable according to the Egecan's guide. Now I switched to EventTable.

**Comment by halil-gurbuz** [comment]
EventTable is also completed.

**Comment by egecans** [comment]
It is all completed
