### ISSUE TITLE
Mobile - Creating Resource Table in Local Database

### ISSUE THREAD

**Issue by HasanBingolbali** [bounswe/bounswe2023group2#345]
### Issue Description

We need to store Resource entity in the local database for offline need creation. I am designed to create Resource table for that

### Deadline of the Issue

24.10.2023

### Reviewer

Egecan Serbester

**Comment by egecans** [comment]
I created this for Hasan in this [commit](https://github.com/bounswe/bounswe2023group2/commit/92e9e06bfea4aea64d468eb76b428d06c35aa360)  because he tried extra to connect the backend.

**Comment by egecans** [comment]
It is finished with #446
