### ISSUE TITLE
BE-Documentation-Guide for Swagger UI of our API

### ISSUE THREAD

**Issue by mehmetkuzu** [bounswe/bounswe2023group2#358]
### Issue Description

Swagger is a nice and appropriate tool to share the information about the endpoints. 

BE team can use it for some simple tests with specific data.

FE and MO team can use it as a guide to write their own API calls in the client code.

A simple and short document to advise the teams about Swagger use will be useful.

### Deadline of the Issue

21.10.2023

### Reviewer

Hasan Bingölbali

**Comment by bgmrsln** [comment]
I am not sure if we really need Swagger. Last semester we were using the Postman. Anyone can explain the differences?

**Comment by mehmetkuzu** [comment]
I used Swagger actually. I guess with Postman you have more control. 
On the other side FastAPI has its Swagger interface automatically.

We dont have to decide on a common tool. 

I thought we may need to advise on using such a tool. But its not that much important. 

I am closing the issue.
