### ISSUE TITLE
Research certain github features

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#36]
### Issue Description

Following github features should be searched since they will be used:
- [x] [Discussions](https://docs.github.com/en/discussions)
- [x] [Milestone](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones)
- [x] [Project](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects)

### Deadline of the Issue

21.03.23

### Reviewer

Begüm Arslan

**Comment by cahidenes** [comment]
I can make some research about these topics and prepare a presentation if it is OK.

**Comment by bgmrsln** [comment]
A small presentation would be useful for the meeting at Thursday. But It is not a must.
