### ISSUE TITLE
Backend - Container bugfix

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#362]
### Issue Description

Mongo container can be connected when backend is build with uvicorn, but problem arises when both are containers. 

### Deadline of the Issue

21.10.2023

### Reviewer

Merve Gürbüz

**Comment by bgmrsln** [comment]
Problem is found in the URL: 
<img width="416" alt="image" src="https://github.com/bounswe/bounswe2023group2/assets/53114791/1486c7a9-0058-4549-8ba6-9303210af81f">
https://stackoverflow.com/questions/7744147/pymongo-keeps-refusing-the-connection-at-27017 explains .

**Comment by mehmetkuzu** [comment]
We can close the issue.
But before that I guess we should change the issue title.

Bugfix on BE code regarding the container use.
olabilir.

**Comment by mervegrbz** [comment]
If it works with this config we can go with that, but I will search what it happens like that since it works on my machine ahahaah
