### ISSUE TITLE
How to store images?

### ISSUE THREAD

**Issue by mehmetkuzu** [bounswe/bounswe2023group2#372]
### Issue Description

We have images and image data for various purposes in DARP. Alternatives:
1. We can store images in the database. (BSON variables)
2. We can have a filestore for images, videos etc. and store links to images in the database (string fields of paths)

Just had a quick glimpse for this issue.
- This one is a short article of [Ken Alger](https://www.mongodb.com/developer/author/ken-w-alger/) an engineer working in Mongo 
https://www.mongodb.com/developer/products/mongodb/storing-large-objects-and-files/

What should be our solution?

### Deadline of the Issue

23.10.2023

### Reviewer

Hasan Bingölbali

**Comment by mervegrbz** [comment]
I have these options in my mind:
- storing as base64 in db, (not the good one, it will drastically affect db performance)
- storing at s3 (it has free usage probably it will be efficient)
where will we use images, I only remember profile photo but I am not sure if user will have or not

**Comment by mehmetkuzu** [comment]
> I have these options in my mind:
> 
> * storing as base64 in db, (not the good one, it will drastically affect db performance)
> * storing at s3 (it has free usage probably it will be efficient)
>   where will we use images, I only remember profile photo but I am not sure if user will have or not

Only profile photos as far as I see. So I agree, storing as files might be better.

**Comment by mehmetkuzu** [comment]
Ah. One more use: Again for user profiles, the document image for the user skill. (Diploma, certificate etc)
But still storing as image is ok.

**Comment by bgmrsln** [comment]
Do we really need profile images? I can't see the reason

**Comment by mehmetkuzu** [comment]
> Do we really need profile images? I can't see the reason

For real life implementation, I guess yes. User profile pictures (Actually their photos) might be an important part of individual data.

On the other hand, we should be implementing something including photos, images. Just for practice. (And the project's complexity)

**Comment by egecans** [comment]
> Do we really need profile images? I can't see the reason

It also would be beneficial the cases when the person shows him/herself as a resource. Because needy ones may not know him without a profile picture.

**Comment by bgmrsln** [comment]
It is done, closing the issue
