### ISSUE TITLE
Mobile - User Classes

### ISSUE THREAD

**Issue by cahidenes** [bounswe/bounswe2023group2#373]
### Issue Description

User Classes will be created according to the class diagram [here](https://lucid.app/lucidchart/fb7d07fe-1069-477f-99c0-3ced3182c275/edit?invitationId=inv_179721cc-4873-471d-85af-7a87386d637c&page=0_0#). Following classes will be created:

- [x] AuthenticatedUser
- [x] CredibleUser
- [x] RoleBasedUser

The hierarchy between these classes should be like in the class diagram.

The need for these classes emerged during issue #335.

### Deadline of the Issue

23.10.2023

### Reviewer

Halil İbrahim Gürbüz

**Comment by cahidenes** [comment]
This issue is resolved with #375

**Comment by halil-gurbuz** [comment]
This feature branch is merged with main, I closed this issue.
