### ISSUE TITLE
Backend - Test: Authentication endpoints

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#379]
## Description
We will develop unit tests for the newly implemented Authentication endpoints, ensuring comprehensive coverage by considering potential edge cases.
- [x] #433
- [x] #447
- [x] #448

## Deadline
28.10.2023

**Comment by bgmrsln** [comment]
Implementations under BE/test/authentication branch

**Comment by bgmrsln** [comment]
Related pr: https://github.com/bounswe/bounswe2023group2/pull/450
