### ISSUE TITLE
Backend - Test: Need CRUD Endpoints

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#381]
## Description
We will develop unit tests for the newly implemented Need endpoints, ensuring comprehensive coverage by considering potential edge cases.

## Deadline
28.10.2023

**Comment by azizamankenova** [comment]
We have implemented 16 tests that cover all potential cases. The [PR #467](https://github.com/bounswe/bounswe2023group2/pull/467) was created and approved. The issue can be closed
