### ISSUE TITLE
Mobile - Simple map page initialization

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#383]
## Description
A basic map page for the mobile application must be initialized, ensuring its proper integration and smooth functionality across various mobile device screen sizes.

## Date
14.11.2023

**Comment by HasanBingolbali** [comment]
We had a mock map in milestone 1 and it is represented and issue can be closed

**Comment by egecans** [comment]
We will implement a real map instead of mock ss for presentation, therefore I am reopening this issue.

**Comment by egecans** [comment]
I'm closing this issue since it's implemented in #509
