### ISSUE TITLE
Frontend - CRUD Activity Pages

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#385]
## Description
Pages for activity-related CRUD operations (both 'need' and 'resource' categories) must be initialized on the frontend, ensuring that the objects can be created, displayed, updated and deleted.

## Deadline
31.10.2023

**Comment by mervegrbz** [comment]
We have extended this issue, since this issue is too wide

**Comment by mervegrbz** [comment]
We have separated the task defined in here in issue #492 #487
