### ISSUE TITLE
Mobile - CRUD Resource Pages

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#387]
## Description
Pages for resource-related CRUD operations must be initialized on the mobile, ensuring that the objects can be created, displayed, updated and deleted.

Its subissues are:
- [x] #412
- [x] #413
- [x] #414

## Deadline
31.10.2023

**Comment by HasanBingolbali** [comment]
they are closed with. For detailed info check: https://github.com/bounswe/bounswe2023group2/pull/446#issue-1968980996

**Comment by higurbuzz** [comment]
Since all the tasks are done, I am closing this issue.
