### ISSUE TITLE
Frontend - Milestone 1 review

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#388]
## Description
A review of Milestone 1 for the Frontend team will be conducted, ensuring that all objectives and deliverables outlined in the project plan so far have been met and are functioning as expected.

## Date
29.10.2023

**Comment by mervegrbz** [comment]
We have synced the Pr s and talked about the design of the pages.

**Comment by mervegrbz** [comment]
I accidentally close the wrong issue, sorry

**Comment by canbora** [comment]
We seem to have forgotten to close this issue after the review.
