### ISSUE TITLE
Mobile - Milestone 1 Review

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#389]
## Description
A review of Milestone 1 for the Mobil team will be conducted, ensuring that all objectives and deliverables outlined in the project plan so far have been met and are functioning as expected.

## Date
29.10.2023

**Comment by egecans** [comment]
It's ok for mobile as far as I see.

I added this for deliverables, but I think that's not the purpose. Anyway, the summary of what we did is here.
*Mobile*
 
- Added a simple homepage, toggle bar, navbar to navigate to other pages.
- The UI part of the profile section was implemented with dummy information.
- Network manager was created for backend connection. In this way; authentication, and resource need connection was provided easily.
- Page layouts are created. Decided where to go from which page and showed with simple pages.
- Login and registration for authentication were completed by connecting to the back-end. The UIs of forgot password, change password sections are ready, waiting for back-end to make end-points.
- A simple maps page was created for the customer to visualize.
- Need, Resource, Action, Event, Emergency and Profile tables were created for the local database in accordance with MVVM. Connection with UI is provided through ViewModels. These objects are defined and called in a single place with Dependency Injection.
- Creation forms were prepared for Need and Resource.
- Resource Entities created in the form of adding Resource were stored in the database in the back-end and all stored resource objects were shown on the Resource page with recycler-view.
- Need Entities created in the Need addition form were stored in the local database and shown with recycler-view on the Need page.
