### ISSUE TITLE
Backend - Improvements Need CRUD and additional endpoints

### ISSUE THREAD

**Issue by busetolunay** [bounswe/bounswe2023group2#400]
Improvements Need CRUD and additional endpoints

**Comment by busetolunay** [comment]
I added get and set methods for urgency field in need . I also reviewed Aziza's code. Everything seems fine. Also created a pull request and merged the branches after the approval.

**Comment by azizamankenova** [comment]
In addition to CRUD, additional endpoints for getting and setting initial and unsupplied quantities are implemented. The implementation can be found in this PR #392. I have also reviewed Buse's code for getting and setting urgency. The issue can be closed
