### ISSUE TITLE
Backend - Improvements Resource CRUD and additional endpoints

### ISSUE THREAD

**Issue by azizamankenova** [bounswe/bounswe2023group2#404]
### Issue Description

Continue work on resource CRUD and implement additional endpoints.

### Deadline of the Issue

27.10.23

### Reviewer

None

**Comment by rburaksaritas** [comment]
New endpoints mentioned in the Class Diagram are added in the [branch](https://github.com/bounswe/bounswe2023group2/tree/BE/feature/resource-additional-endpoints).
