### ISSUE TITLE
Create Mockups

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#41]
### Issue Description

Create Mockups to show requirements better to project owner
- [x] Create the page and add it to sidebar

Create mockups for following topics:
- [x] #42
- [x] #43
- [x] #44
- [x] #45

### Deadline of the Issue

21.03.2021

### Reviewer

Begüm Arslan

**Comment by egecans** [comment]
I added Account Features mock-ups which we have created with Begum below Account Features in [mock-up page](https://github.com/bounswe/bounswe2023group2/wiki/Mockups)

**Comment by bgmrsln** [comment]
Further mockups are needed for Needs, Resources, Actions and Events.

**Comment by bgmrsln** [comment]
I will be working on a resource entry mockup.

**Comment by halilgurbuz** [comment]
Add need and add event mockups are done. #43

**Comment by bgmrsln** [comment]
Since all items are checked, I am closing the issue.
