### ISSUE TITLE
Mobile - Login and Registration Connecting into Backend

### ISSUE THREAD

**Issue by egecans** [bounswe/bounswe2023group2#411]
### Issue Description

When a user is registered it should connect to the backend and this user should be created on the backend. After the user is created successfully, the user can log in to the system. When the user logs in, it should redirect to the home page. 
When a user logs in, his/her token should be stored in SharedPref, this shared pref should be used for posting methods on the backend. Moreover, when a user logs out, its token should be deleted from sharedPref and redirected to the login page.

### Deadline of the Issue

28.10.2023

### Reviewer

Egecan Serbester

**Comment by HasanBingolbali** [comment]
Completed with related pr #434
