### ISSUE TITLE
Milestone 1 - Prepare Deliverables

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#419]
## Description
Deliverables content must be prepared for the Milestone 1. 

## Deadline
03.11.2023

**Comment by bgmrsln** [comment]
I have started working on deliverables here: https://hackmd.io/a7yGOPYRS7-Qf-z7CF4hxw

**Comment by bgmrsln** [comment]
Added RAM to wiki as images:  https://github.com/bounswe/bounswe2023group2/wiki/RAM

**Comment by bgmrsln** [comment]
Added [deliverables list](https://hackmd.io/a7yGOPYRS7-Qf-z7CF4hxw#Deliverables) and requirements that were implemented in this milestone

**Comment by rburaksaritas** [comment]
Milestone 1 Deliverables report is uploaded to the main repository.
