### ISSUE TITLE
Account Features

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#42]
Create mock ups for account features:
- [x] login page
- [x] sign up page
- [x] reset password page

**Comment by egecans** [comment]
We created these mock ups with Begum.

**Comment by egecans** [comment]
We created these mock ups with Begum

**Comment by mervegrbz** [comment]
I reopened the issue :( . Since the platform will also be served as website we need to add mockups for it too

**Comment by halilgurbuz** [comment]
Email and mobile number options are written on the password reset screen. However, there is no mobile number field on the sign-up screen. We can also pay attention to this for consistency.

**Comment by bgmrsln** [comment]
I agree with @halilgurbuz, we should add phone number.

**Comment by egecans** [comment]
Well, this was optional actually. The sign-up page is for every user that wants to be registered on our platform. We shouldn't ask for their mobile number on the registration page, I think. They can edit their profile and add their mobile number after they are registered. If they add their mobile number they can also reset their password with the link that comes to their mobile phone beside their email.
