### ISSUE TITLE
Milestone 1 - Deployment

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#420]
## Description
Deployment content must be prepared for the Milestone 1. 

## Deadline
31.10.2023

**Comment by bgmrsln** [comment]
The software you have been developing so far should be prepared with good practices in mind
(e.g., documentation, tests, etc.) and committed to the repository appropriately (e.g., merged
with pull requests, reviewed before a merge, containing good commit messages).
The software must be dockerized and deployed.
Create a pre-release version of your software that marks this version (check out how you
create a release in GitHub):
Release Name: 0.1.0-alpha (pre-release option)
Release Description: Brief description of requirements that are covered
Tag name: customer-milestone-1
Your release should include the android package file ( .apk ).
All instructions for building and running the software should be provided, including the
docker build instructions and environment variables, if any. A fresh programmer that is
fluent with various programming tools but not docker itself nor your project, should be able
to do the deployment (for both web and mobile) by just following your steps.

**Comment by mervegrbz** [comment]
I have done the deployment for now. I will deploy the last version after the release

**Comment by egecans** [comment]
Since deployment is done successfully, I'm closing that.
