### ISSUE TITLE
signUp api response inconsistency

### ISSUE THREAD

**Issue by HasanBingolbali** [bounswe/bounswe2023group2#435]
### How To Reproduce: 

<img width="710" alt="Screenshot 2023-10-29 at 02 45 53" src="https://github.com/bounswe/bounswe2023group2/assets/74209102/a0b69f26-e16a-4786-ab24-f1f826caf0c7">

### Expected response body 

Status code: 422
{
  "detail": [
    {
      "loc": [
        "string",
        0
      ],
      "msg": "string",
      "type": "string"
    }
  ]
} 

### Deadline of the Issue

31.10.2023

### Reviewer

Hasan Bingölbali

**Comment by bgmrsln** [comment]
We declared that we will return error codes as: 
`    HTTP/1.1  404
    Content-Type: application/json
    {
      "ErrorMessage": "User not updated",
      "ErrorDetails": "Duplicate record for profile languages for User: Cezmi Baskın"
    }` 
in https://github.com/bounswe/bounswe2023group2/wiki/API-conventions . And after discussion, we decided that error status should be 400, so I will be changing response to this format

**Comment by HasanBingolbali** [comment]
> We declared that we will return error codes as: ` HTTP/1.1 404 Content-Type: application/json { "ErrorMessage": "User not updated", "ErrorDetails": "Duplicate record for profile languages for User: Cezmi Baskın" }` in https://github.com/bounswe/bounswe2023group2/wiki/API-conventions . And after discussion, we decided that error status should be 400, so I will be changing response to this format

I highly suggest sticking to the response body [In the docs](http://3.218.226.215:8000/docs#/users/login_for_access_token_api_users_login_post) : {
  "detail": [
    {
      "loc": [
        "string",
        0
      ],
      "msg": "string",
      "type": "string"
    }
  ]
}

**Comment by mehmetkuzu** [comment]
> > We declared that we will return error codes as: ` HTTP/1.1 404 Content-Type: application/json { "ErrorMessage": "User not updated", "ErrorDetails": "Duplicate record for profile languages for User: Cezmi Baskın" }` in https://github.com/bounswe/bounswe2023group2/wiki/API-conventions . And after discussion, we decided that error status should be 400, so I will be changing response to this format
> 
> I highly suggest sticking to the response body [In the docs](http://3.218.226.215:8000/docs#/users/login_for_access_token_api_users_login_post) : { "detail": [ { "loc": [ "string", 0 ], "msg": "string", "type": "string" } ] }

Hasan, last format you mentioned is not our convention. It is the convention for validation of parameters by FastAPI.
So your check should include:
If the response_code is 422 (Validation error) that means your parameters are missing or in wrong format. There is nothing we can do about this.
But all other responces (including other exceptions) do stick to our convention in 

https://github.com/bounswe/bounswe2023group2/wiki/API-conventions

**Comment by HasanBingolbali** [comment]
Please add every possible response to the swagger document. Also, keep in mind that frequent change of swagger documents really slows the development for api-dependent platforms. Thank you

**Comment by mehmetkuzu** [comment]
> Please add every possible response to the swagger document. Also, keep in mind that frequent change of swagger documents really slows the development for api-dependent platforms. Thank you

Now we came to solution:

- The API Conventions document will be used as a guide by Backend Team
- The documentation of the functions will be available on swagger. (As Hasan requested.)

If that's ok for all, we can close the issue.

![swaggerimage](https://github.com/bounswe/bounswe2023group2/assets/46297916/fea1e5cc-5f49-4188-a632-386d53e1e814)

**Comment by HasanBingolbali** [comment]
That seems perfect, closing the issue

**Comment by bgmrsln** [comment]
Related pr: https://github.com/bounswe/bounswe2023group2/pull/438
