### ISSUE TITLE
Backend - Bugfix for resource and need get

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#451]
### Issue Description

Our requirements allow resource get  and need get without log in. Related endpoints should be updated.

Related requirements:
1.1.2.1.2 Guest users shall be able to view emergencies and activities about disasters, including event types, resources available, and actions taken.
1.1.2.1.3 Guest users shall be able to filter and sort activities about emergencies, events, resources, actions, and needs based on location, date, type etc.

### Deadline of the Issue

30.10.2023

### Reviewer

Begüm Arslan

**Comment by rburaksaritas** [comment]
Get methods for both need & resource are made available publicly.
