### ISSUE TITLE
Create System Requirements

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#47]
### Issue Description

System requirements with the following headers should be written:
- [x] #48
- [x] #57
- [x] #50
- [x] #52
- [x] #53
- [x] #54
- [x] Filter,sort, search
- [x] Map visualization
- [x] #59
- [x] #49
- [x] Administration

### Deadline of the Issue

21.03.2023

### Reviewer

Begüm Arslan

**Comment by mehmetkuzu** [comment]
1. The sections in the first draft up to the end of Introduction should be copied to requirements second draft. (Just before process.)
2. Seems that @Aras Güngöre added his share of Introduction to the first draft.
