### ISSUE TITLE
Backend - Action implementation

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#477]
### Description
Backend CRUD endpoints for Action must be implemented:

- [x] POST
   - [x] create action with action model
- [x] GET
   - [x]  Get all actions
   - [x] Get action by action id
   - [x] get related group(need,resource tuples) info by need id
- [x] PUT
   - Update an action's certain fields - (decided to not do this one due to its complexity)
   - [x]  action done for updating resource and need status
- [x] DELETE
   - [x] delete an action
   - [x] Cancel an action

Ensure endpoints have validation and return appropriate status codes as stated in the [API convention document](https://github.com/bounswe/bounswe2023group2/wiki/API-conventions).

### Deadline
30.11.2023

**Comment by bgmrsln** [comment]
PR is ready: https://github.com/bounswe/bounswe2023group2/pull/577

**Comment by bgmrsln** [comment]
PR is merged so closing the issue
