### ISSUE TITLE
Backend - User role implementation

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#478]
### Description
User roles implementation must be implemented.

Ensure endpoints have validation and return appropriate status codes as stated in the [API convention document](https://github.com/bounswe/bounswe2023group2/wiki/API-conventions).

### Deadline
15.11.2023

**Comment by bgmrsln** [comment]
Following endpoints should be implemented:
* POST /proficiency-request (which will be saved to database for an admin to view ), it should have ProfRequest in the body which consists of username, proficiency, documentation and details. 
* GET /user-role
(admin should later have GET /role-verification-requests and POST /verify-user)
(credible users also should be set by admins by POST /add-credible-user)

**Comment by bgmrsln** [comment]
added an initial adding proficiency, a document of proof should also be asked. But since we did not implement the image of pdf upload mechanism, that part is missing: 
<img width="554" alt="image" src="https://github.com/bounswe/bounswe2023group2/assets/53114791/348ef4c1-cd02-42de-9fe7-bf768d625e63">

**Comment by bgmrsln** [comment]
https://github.com/bounswe/bounswe2023group2/pull/505

**Comment by bgmrsln** [comment]
Changed the structure of role-based users and added proficiency to user models: https://github.com/bounswe/bounswe2023group2/pull/505
<img width="745" alt="image" src="https://github.com/bounswe/bounswe2023group2/assets/53114791/67480ba0-364a-4f40-94be-2dc8f409191f">

**Comment by bgmrsln** [comment]
PR is merged closing the issue
