### ISSUE TITLE
Frontend - Email verification page design and implementation

### ISSUE THREAD

**Issue by canbora** [bounswe/bounswe2023group2#479]
### Description
Webpages for email verification should be implemented

### Deadline
15.11.2023

**Comment by mervegrbz** [comment]
The email verification needs backend development, we are waiting for it to be completed as frontend

**Comment by mervegrbz** [comment]
I have done the necessary changes on the the password reset #766 , just the implementation of the form has left, I will complete this in the branch `action-revisit`. I am closing the issue since main deliverables has derived
