### ISSUE TITLE
Backend Team Meeting #4

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#481]
Backend team meeting 4 will be held on 9.11.2023.

- [ ] Mehmet Kuzulugil
- [ ] Begüm Arslan
- [ ] Aziza Mankenova
- [ ] Ramazan Burak Sarıtaş
- [ ] Buse Tolunay

### Date
9.11.2023

**Comment by bgmrsln** [comment]
https://github.com/bounswe/bounswe2023group2/wiki/Backend-Team-Meeting-(Offline)-%234 meeting notes can be found here
