### ISSUE TITLE
Backend - Requirements and design documents study

### ISSUE THREAD

**Issue by mehmetkuzu** [bounswe/bounswe2023group2#483]
### Issue Description

The design and coding elements for the upcoming milestone is more complicated compared to Milestone 1. 
So regarding the following points, the requirements and design should be studied by the team members:

- [x] Events
- [x] Resource
- [x] Need
- [x] User Roles
- [x] Admin
- [x] Feedback
- [x] Filter/sort

### Deadline of the Issue

11.11.2023

### Reviewer

None

**Comment by bgmrsln** [comment]
Additionally I have studied user role requirements. I have noticed some parts are not clarified for the code implementation. So I will bring up those topics to the next meeting. Such as:
* do we require an admin check for role based user documents
* do we require role based user documents
* should we support pdf and jpg file types
* should credible users directly set by admin users
* is credible user only related to priority of the activities
* should we allow multiple proficiencies? I believe for system simplicity, no (but it can also cause one person can be only a english speaker in the system)
* will we keep guest users in the database?
*

**Comment by mehmetkuzu** [comment]
Reviewing the events: 
- Although the concept of events has been defined and understood by the group last season the documentation has some weak points. 
- Class diagram should be eloberated for this reason.

**Comment by rburaksaritas** [comment]
I noted some points about Resource and Need, and started implementing the missing features, for example created and last updated dates tracking is added to both. Currently in PR #553 and #558.

**Comment by bgmrsln** [comment]
We review and update some of the requirements, it seems done as of now
