### ISSUE TITLE
Deciding Activity attributes for activity information card on map page

### ISSUE THREAD

**Issue by Sahin-Albayram** [bounswe/bounswe2023group2#488]
### Issue Description

For the pop up design on the map page, planning is needed on how the activities will be kept in the database and which information will be shown on the front page
- [x] https://github.com/bounswe/bounswe2023group2/issues/521

### Deadline of the Issue

15.11.2023

### Reviewer

Egecan Serbester

**Comment by bgmrsln** [comment]
I believe each resource and its subtype and its subtypes subtype requires different attention. Here is my idea of Food resource and clothes resource: 
![WhatsApp Image 2023-11-13 at 21 46 58 (1)](https://github.com/bounswe/bounswe2023group2/assets/53114791/4f601b6c-33d6-4a4a-a2b4-858764e7d410)
![WhatsApp Image 2023-11-13 at 21 46 58](https://github.com/bounswe/bounswe2023group2/assets/53114791/eec32d22-6b50-4a77-8c7b-149a656df184)
