### ISSUE TITLE
Backend - Milestone 2 Plan Review

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#489]
### Description

Backend team will review the plan for Milestone 2 related works.

### Deadline

11.11.2023

**Comment by bgmrsln** [comment]
We will be implementing mainly 4 acitivity types(resource, need, action, event) and filter/sort. We will also be working on user-roles, feedback mechanism, email verification, image uploading, emergency form as much as time allows. First two implementation is the main functionality of our projecti so they are prioritized. My review is done.

**Comment by rburaksaritas** [comment]
We will finalize the design and implementation of resource and need, I started working on the predefined subtypes part.

**Comment by mehmetkuzu** [comment]
Some details should also be revisited.
- We decided to store URLs for documents (ie. images or pdf files). So the create operation will actually consist of storing a binary data to some file resource on the internet (resulting a URI)  and the retrieve operation will return the URL of this resource.
- Unit test codings should be a part of the coding process this time. (Honestly I've done most of the unit test coding after finishing all coding for all parts. Should have done the other way.)
