### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#49]

**Comment by bgmrsln** [comment]
Can you check the system requirements related to notifications @HasanBingolbali . I added some items similar to yours. We can decide on wheteher more should be added and how it would be more clear

**Comment by bgmrsln** [comment]
You can close the issue after you check, we can discuss it further at the upcoming meeting.

**Comment by HasanBingolbali** [comment]
Comprehensive and great work!
