### ISSUE TITLE
Create Personal Introduction Wiki Pages

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#5]
Each group member should write a wiki page, introducing who they are. Check below when the page is completed.
- [x] [Begüm Arslan](https://github.com/bounswe/bounswe2023group2/wiki/Beg%C3%BCm-Arslan)
- [x] [Merve Gürbüz](https://github.com/bounswe/bounswe2023group2/wiki/Merve-G%C3%BCrb%C3%BCz) 
- [x] [Cahid Enes Keleş](https://github.com/bounswe/bounswe2023group2/wiki/Cahid-Enes-Kele%C5%9F)
- [x] [Aras Güngöre](https://github.com/bounswe/bounswe2023group2/wiki/Aras-G%C3%BCng%C3%B6re)
- [x] [Ersel Çanakçılı](https://github.com/bounswe/bounswe2023group2/wiki/Ersel-Çanakçılı)
- [x] [Egecan Serbester](https://github.com/bounswe/bounswe2023group2/wiki/Egecan-Serbester)
- [x] [Mehmet Emin İpekdal](https://github.com/bounswe/bounswe2023group2/wiki/Mehmet-Emin-İpekdal)
- [x] [Halil İbrahim Gürbüz](https://github.com/bounswe/bounswe2023group2/wiki/Halil-İbrahim-Gürbüz)
- [x] Ömer Şahin Albayram
- [x] Hasan Bingölbali
- [x] [Ramazan Burak Sarıtaş](https://github.com/bounswe/bounswe2023group2/wiki/Ramazan-Burak-Sar%C4%B1ta%C5%9F)

Revisor: @bgmrsln 
Deadline: 07.03.2023

**Comment by rburaksaritas** [comment]
Please link your personal page to your name in "Team Members" section.
