### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#50]
System requirements related to resources must be clarified with this issue.

**Comment by bgmrsln** [comment]
Added some requirements under [it](https://github.com/bounswe/bounswe2023group2/wiki/Requirement-draft-2). Can you revise and improve it with question mark and comments @cahidenes ? So we can discuss it at the meeting

**Comment by cahidenes** [comment]
Done. Here is a [link for comparison](https://github.com/bounswe/bounswe2023group2/wiki/Requirement-draft-2/_compare/c4978ae192b64f6bc5afcd5f2f5914b5dbace394...0baeabe55c1628e1426c8e6f19697bcb8b5a6f3d)

**Comment by rburaksaritas** [comment]
I just added some details to 1.2.3.2. Resource Structure to clarify and branch out some points.
