### ISSUE TITLE
Mobile - Delete Need and Resources

### ISSUE THREAD

**Issue by egecans** [bounswe/bounswe2023group2#501]
### Issue Description

Users should be able to delete the resources and needs they see on their home page by connecting to the backend. When the user wants to delete it, a dialog should be opened and the user selection should be asked again.

### Deadline of the Issue

13.11.2023

### Reviewer

Cahid Enes Keleş

**Comment by egecans** [comment]
We have to decide whether the delete button will be next to the recycler view item or on the page after clicking on the item.
If the backend handles only the users that create that resource/need to delete this item, we need to show this button only for these resources and needs.

**Comment by HasanBingolbali** [comment]
Closed with https://github.com/bounswe/bounswe2023group2/pull/622
