### ISSUE TITLE
Test -Backend - Action CRUD endpoints

### ISSUE THREAD

**Issue by busetolunay** [bounswe/bounswe2023group2#517]
Tests for action endpoints needs to be written for following endpoints:
- [x] POST
   - [x] create action with action model
- [x] PUT
   - [x]  Cancel an action
   - [x] Do an action

**Comment by bgmrsln** [comment]
I wrote initial tests as above. Also did postman tests including other endpoints: https://darp-354343.postman.co/workspace/Team-Workspace~323ad32b-b319-4a0d-8ebe-e9ebe4c0a14d/folder/25451471-0f5f9e91-5254-4345-a774-c14deeecbca4?ctx=documentation
