### ISSUE TITLE
Backend - Admin CRUD and specific endpoint implementations

### ISSUE THREAD

**Issue by busetolunay** [bounswe/bounswe2023group2#519]
## Description
We will develop admin endpoints as stated in the requirements.
Ensure endpoints have validation and return appropriate status codes as stated in the [API convention document](https://github.com/bounswe/bounswe2023group2/wiki/API-conventions).

## Deadline
26.11.2023

**Comment by azizamankenova** [comment]
PR #621 includes admin related endpoints. The issue can be closed.
