### ISSUE TITLE
Needs

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#52]
Create the system requirements for needs

**Comment by bgmrsln** [comment]
I added some requirements under [this](https://github.com/bounswe/bounswe2023group2/wiki/Requirement-draft-2). Can you revise and improve it @halilgurbuz , I am not sure about the format?

**Comment by mehmetkuzu** [comment]
Both needs and resources should be defined as a list.
(One should be able to ask for more thane one goods/instruments/experts etc. in one need declaration. 
Or we should have a page to enter a list at once and the needs on the list are seperate need entries related to this user declaration.)

**Comment by mervegrbz** [comment]
Since there are no further activities for this issue and issue aim has been reached, I am closing this one.
