### ISSUE TITLE
Backend - Filter (Resource and Need)

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#566]
Filtering should be done based on:
activity_type-> subtype filters-> subtype_filters
- [x] Get API s that returns filters should be made for each layer.
- [x] Get APIs taht actually filters and returns the activity list should be made

**Comment by rburaksaritas** [comment]
I decided to directly modify the get_all functions to accept optional filter and sort queries instead of creating a new endpoint. It will still accept default request without any parameters.

**Comment by rburaksaritas** [comment]
#### Query Parameters:
- `types`: A list of types to filter the resources. 
  - `/api/resources?types=food` 
  - `/api/resources?types=food,cloth`
- `subtypes`: A list of subtypes for more specific filtering. 
  - `/api/resources?subtypes=bread`
  - `/api/resources?subtypes=bread,water,milk`
- `active`: A boolean to filter by active/inactive status. `
  - `/api/resources?active=true`
  - `/api/resources?active=false`
  
 #### Example
 `/api/needs?active=true&types=drink&subtypes=water,milk`

##### Can be sorted after, as  `/api/needs?active=true&types=drink&subtypes=water,milk&sorty_by=upvotes&order=desc`
