### ISSUE TITLE
Mobile - Choose Location Through Map View

### ISSUE THREAD

**Issue by cahidenes** [bounswe/bounswe2023group2#572]
### Issue Description

Currently location fields in the add / edit activity pages take input as plain text. However, choosing location should be easy. In order to achieve that, location select should be done through map view.

### Deadline of the Issue

28.11.2023

### Reviewer

None

**Comment by higurbuzz** [comment]
It is merged with main in [PR618](https://github.com/bounswe/bounswe2023group2/pull/618). I am closing the issue.
