### ISSUE TITLE
Backend - Implement the check for the coordinates of resources and needs

### ISSUE THREAD

**Issue by aziza-m** [bounswe/bounswe2023group2#584]
### Issue Description

Upon creation of a resource, it was giving an error, as if some fields were missing because of coordinates that were 0.
The check for the coordinates should be implemented to be mandatory and within the range. Also the quantities should be greater than 0

### Deadline of the Issue

23.11.2023

### Reviewer

Mehmet Kuzulugil

**Comment by azizamankenova** [comment]
Since the PR #594 was successfully merged. The issue can be closed
