### ISSUE TITLE
Backend - Bugfix - datetime.date cannot be inserted into mongodb

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#597]
### Issue Description

it gives an error due to datetiem.date fields of resource model: bson.errors.InvalidDocument: cannot encode object: datetime.date(2023, 11, 23), of type: <class 'datetime.date'>

### Deadline of the Issue

24.11.23

### Reviewer

Begüm Arslan

**Comment by rburaksaritas** [comment]
Appearently we have to make it datetime.datetime instead of datetime.date. I will take a look at it as soon as I can.
