### ISSUE TITLE
Modify README

### ISSUE THREAD

**Issue by mervegrbz** [bounswe/bounswe2023group2#6]
We need to modify  repository README file since the first impression is the key. README needs to contain:
-  Description of the project
- List of team members

**Due Date: 09.03.2023**
**Revisor: @erselcanakcili **

**Comment by mervegrbz** [comment]
I think we can add team members as contributers for now, and also you may want to mention our motivation and project description as seperately. Good job  :star_struck:

**Comment by cahidenes** [comment]
The due date is 6 days ago. What are we doing with this issue now?

**Comment by Sahin-Albayram** [comment]
> The due date is 6 days ago. What are we doing with this issue now?

I planned to finish readme after deciding requirement page. However, creating another issue would be better.
