### ISSUE TITLE
Mobile - UI improvements

### ISSUE THREAD

**Issue by higurbuzz** [bounswe/bounswe2023group2#601]
### Issue Description

As the application developed, the need to make changes to the UI arose. Editing the Header and Drawer and adding logos where necessary are some of these.

### Deadline of the Issue

27.11.2023

### Reviewer

Cahid Enes Keleş

**Comment by cahidenes** [comment]
in this [PR](https://github.com/bounswe/bounswe2023group2/pull/650), need page is reorganized.

**Comment by cahidenes** [comment]
Since most of the major UI changes are discussed and done, I am closing this issue.
