### ISSUE TITLE
Mobile - Add Logo

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#607]
Please add our app's new logo to the Mobile app.
PNG and SVG files of the logo can be found [here](https://drive.google.com/drive/folders/1H_64eQqErkKBb36IJ3sUy8euFn-d1rWD?usp=share_link).

**Comment by higurbuzz** [comment]
It is done [PR#611](https://github.com/bounswe/bounswe2023group2/pull/611)
