### ISSUE TITLE
Mobile - Arranging CRUD Needs and Resources

### ISSUE THREAD

**Issue by egecans** [bounswe/bounswe2023group2#610]
### Issue Description

Since Needs and Resource items changed with respect to new dynamic forms, connecting them into backend also should be changed to work properly. Body, Corresponding Item, Backend parsers and utility functions in form should be changed with respect to updates on the backend.

### Deadline of the Issue

26.11.2023

### Reviewer

Halil İbrahim Gürbüz

**Comment by egecans** [comment]
Needs are handled in this PR #624

**Comment by higurbuzz** [comment]
All is done, good job. I am closing the issue.
