### ISSUE TITLE
Mobile - Profile Redirect Login

### ISSUE THREAD

**Issue by cahidenes** [bounswe/bounswe2023group2#632]
### Issue Description

When logged out, profile page can redirect the user to the log in page. Therefore, navbar will be no longer needed. So the navbar will be removed.

### Deadline of the Issue

28.11.2023

### Reviewer

None

**Comment by higurbuzz** [comment]
It is done in [PR633](https://github.com/bounswe/bounswe2023group2/pull/633). Good job.
