### ISSUE TITLE
Translation - Language pack files should be prepared in various languages

### ISSUE THREAD

**Issue by mehmetkuzu** [bounswe/bounswe2023group2#678]
### Issue Description

Frontend and Mobile sub teams will provide their "dictionaries" consisting of terms of UI.
The translations should be done and managed for general ues.

### Deadline of the Issue

17.12.2023

### Reviewer

Merve Gürbüz

**Comment by mehmetkuzu** [comment]
We are collecting the vocabulary (words, terms and phrases). The methodology has started to appear.

**Comment by busetolunay** [comment]
done and created a pull request
