### ISSUE TITLE
Updating Wiki main page

### ISSUE THREAD

**Issue by Sahin-Albayram** [bounswe/bounswe2023group2#68]
### Issue Description

Since we have added new pages in wiki. Updating wiki is necessary

### Deadline of the Issue

28.03.2023

### Reviewer

Ömer Şahin Albayram

**Comment by Sahin-Albayram** [comment]
How can we enrich contents of page in order to make it more abundant (hope that this is the right word for it)? Right side of main page is quite empty

**Comment by mervegrbz** [comment]
I think it is enough for now
