### ISSUE TITLE
Creating meeting template page

### ISSUE THREAD

**Issue by mervegrbz** [bounswe/bounswe2023group2#7]
We need to decide on meeting template and document it on a page. Plan should provide:

- [ ] How was the meeting (online ,f2f, ...)
- [ ] What was the communication tools (zoom, discord ...)
- [ ] Where were the meeting
- [ ] Who were the attendees
- [ ] What were the meeting subjects
- [ ] What was decided

**Due date:09.03.2023**
**Revisor: @arasgungore**

**Comment by egecans** [comment]
It is finished. You can check it from [there](https://github.com/bounswe/bounswe2023group2/wiki/Meeting-Template)
