### ISSUE TITLE
Backend - Change vote coefficients

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#725]
### Issue Description

- We have requirements relating to votes, with different coefficients. 

### Deadline of the Issue

19.12.2023

### Reviewer

Begüm Arslan

**Comment by mervegrbz** [comment]
Since aziza is ill this week, Buse will continue on the issue

**Comment by busetolunay** [comment]
Implemented and tested with the help of Aziza who firstly implemented the voting structure
