### ISSUE TITLE
Backend - All Users Endpoint

### ISSUE THREAD

**Issue by cahidenes** [bounswe/bounswe2023group2#726]
### Issue Description

An endpoint that fetches all profiles need to be implemented. The return format of the endpoint should be as follows
```json
{
    "profiles": [
        {
            "username": "string",
            "first_name": "string",
            "last_name": "string"
        }
    ]
}
```

### Deadline of the Issue

19.12.2023

### Reviewer

None

**Comment by bgmrsln** [comment]
We have search_users endpoint. Do we still need this one? @cahidenes

**Comment by cahidenes** [comment]
No, search user endpoint is enough.

**Comment by bgmrsln** [comment]
Done closing the issue
