### ISSUE TITLE
Backend - Adding predefined need type for lost acquaintance

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#742]
### Issue Description

During the Maraş earthquake, lots of information is collected by users that has an acquaintance who might be under rubble. We can enter this need to predefined needs .

### Deadline of the Issue

25.12.2023

### Reviewer

Merve Gürbüz

**Comment by azizamankenova** [comment]
PR #878 is successfully merged. The issue can be closed.
