### ISSUE TITLE
Review Functional Requirements

### ISSUE THREAD

**Issue by egecans** [bounswe/bounswe2023group2#75]
### Issue Description

We have completed the first requirement page. However, the requirements need to be checked in terms of their grammar, scope and comprehensibility. Moreover, there are conflicts between user and system requirements, they should be updated.
We will state updates in comments under this issue.

### Deadline of the Issue

28.03.2023

### Reviewer

Merve Gürbüz

**Comment by egecans** [comment]
Removed requirements:
   1.1.1.1.2 Users should see the data without login. (?)
   1.1.3.7.11.4 Verified users should be able to see a summary of all actions taken by users to help identify areas where additional resources or actions are needed.?
   1.1.3.7.11.5 Verified users shall be able to copy the profile information of a user to another user
   1.2.1.1. A user shall be able to register to the system with minimum attributes
   1.2.1.1.1. E-mail shall be mandatory to register the account. (Not part of the profile information)

Transferred requirements:
   1.1.2.1. Users shall have their profile information recorded. It's transferred to system requirements.
   1.1.2.2. Users shall be able to display profile information details. It's transferred to system requirements
   1.1.2.6  Users shall be able to propose themselves as active resources (within available time limits) according to their profile information. It's transferred to user actions.
   1.3.7.8 "Users shall be able to report malicious users to the admins." transferred to 1.3.7.7.10
Edited requirements:
   1.1.2.3 changed to "Users shall be able to choose their proficiency." instead of system operational-level
   1.1.3.8.5 phone numbers are edited as passwords.
   1.1.3.8.8 deleted  "need logs, event logs, and resources logs" part
   1.2.1.1. optional required parts are added.

Appended requirements: 
1.2.1.2. System should show related actions, needs, resources and events to the authenticated user that has related proficiency. (i.e A doctor should see the event that medications arrive in the area.)

**Comment by bgmrsln** [comment]
Why did we remove the 1.1.1.1.2.?

**Comment by egecans** [comment]
> Why did we remove the 1.1.1.1.2.?


@bgmrsln 
> Why did we remove the 1.1.1.1.2.?
We thought that it was not part of the Account Features. We had already meant it in User Actions 1.1.3.1

**Comment by egecans** [comment]
Removed requirements:
- 1.2.3.1.1. Users shall be able to create, edit and update, or delete resource information. (Because it couldn't state system requirements correctly.)
  - 1.2.4.3 Events should be able to be edited and deleted by the creators.
  - 1.2.4.4 Events should be able to be deleted by admin users. (same as 1.1.4.5)
  - 1.2.4.5 Events should be able to be filtered based on type, location, creator username, etc. (same as 1.1.3.7)
  - 1.2.4.6 Events should be able to be sorted based on date, interaction rate, etc. (same as 1.1.3.7)
  - 1.2.5.3 Actions should be able to be edited and deleted by the creators.
  - 1.2.5.4 Actions should be able to be deleted by admin users if it contains duplicate or false information.
  - 1.2.5.5 Actions should be able to be filtered based on type, location, creator username, etc.
  - 1.2.5.6 Actions should be able to be sorted based on date, interaction rate, etc.
  - 1.2.6.3 Needs shall be edited and deleted by the creators.
  - 1.2.6.4 Needs should be able to be deleted by admin users if it contains duplicate or false needs.
  - 1.2.6.5 Users shall be able to replicate a created need
  - 1.2.6.6 Needs should be able to be filtered based on type, location, etc.
  - 1.2.6.7 Needs should be able to be sorted based on date, urgency, reliability scale, approval number, etc. By default, it will be sorted based on urgency to ensure that the most critical needs are addressed first.

Transferred requirements:


Edited requirements:
1.1.3.3 disasters replaced by events.
1.1.3.4 report required resources related to a disaster replaced by needs in terms of understanding its sense.
1.1.3.8.2 Authenticated users shall create actions.
1.2.7.1 is changed as Events, needs, actions and resources shall be sorted based on location, date, emergency level etc.
1.2.8.2 is changed as The map shall be zoomed in and out. 
Appended requirements:
1.2.3.1.1.  (Platform shall offer some predefined types for a user to select, but the platform shall also let the user enter the type manually in the cases of unexpected types.) is added next to the type
1.1.3.8.3 Authenticated users shall create resources.
1.1.3.8.4 Authenticated users shall update and delete events, actions, resources and needs that they create.

**Comment by egecans** [comment]
Please check the updates on the requirements page and state if you think that some changes are unnecessary.

**Comment by mervegrbz** [comment]
> Why did we remove the 1.1.1.1.2.?

we just changed its place, it is now on user actions

**Comment by egecans** [comment]
> By the way,
> 
> The team can follow the changes using the wiki version control. [I recorded a short video for that:](https://user-images.githubusercontent.com/46297916/228161615-630f428f-ec8f-49ee-8e7e-14e29b995c43.mov)

Thanks for that, now I again made some changes. Please check them from revision and state changes that you think are unnecessary or wrong.

**Comment by bgmrsln** [comment]
[81](https://github.com/bounswe/bounswe2023group2/issues/81) is related to functional requriements related to notifications. I will be adding them to the page

**Comment by mervegrbz** [comment]
We have finished the reviving, closing he issue
