### ISSUE TITLE
Bugfix - Changing Events' coordinates name

### ISSUE THREAD

**Issue by Sahin-Albayram** [bounswe/bounswe2023group2#756]
### Issue Description

In database we hold coordinates of resources and needs as "x,y" however we hold coordinates of events as "center_location_x,center_location_y" can we change it as "x,y" like others ? 

### Deadline of the Issue

20.12.2023

### Reviewer

Ömer Şahin Albayram

**Comment by Sahin-Albayram** [comment]
It might causes some bugs in mobile part of project. Therefore, I can adapt my code to current database if it causes problems.

**Comment by rburaksaritas** [comment]
I am assigning @mehmetkuzu since he was the head of event development. Notified him about the issue, he will take care of it soon.

**Comment by rburaksaritas** [comment]
Closing the issue since @mehmetkuzu did necessary the modifications.
