### ISSUE TITLE
Listing Use Cases

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#78]
### Issue Description

All possible use cases to be included in Use Cases Diagram should be listed to have a starting point. Please share your use case ideas.

### List of Use Cases
Add your proposal and write your name in third column if you want to prepare that use case.

|Name| Description | Group Member  | Status |
|---------|---|:-------------:|----------:|
|Registration |Anyone registers themselves as user| Begüm Arslan | Not started|
|Profile Entry |Registered users enter their own profile information| Mehmet K. | Ready for Revision|
|Profile Editing |Admin users change or verify other users' profile information| Mehmet K. | Ready for Revision|
|Create emergency by guest user | guest user can create emergency | Merve Gurbuz | in-progress|
|Need Entry by Registered user|Registered user declares need| Merve Gurbuz| N/A|
|Event Entry by Registered user|Registered user declares event| Halil İbrahim Gurbuz | Not started|
|Action Entry by Registered user|Registered user declares action| Cahid Enes Keles | Needs Revision |
|List resources by filter for users|Users list declared resources by filter. (included in filter & sort use case diagram)| Ramazan Burak Sarıtaş | Needs Revision|
|Map Use cases |Anyone registers themselves as user| Sahin Albayram | Not started|
|Approve/reject a post (post can be resource need event)| user can reject or approve a post  | Egecan Serbester | in-progress|
|Follow a post/ want notification about post| user can follow a post  | Merve Gurbuz | in-progress|
|Report post's owner to the admin | user can report a post's owner  | Begum Arslan  | ... |
|Delete post (can be done by admin and creator of post) | admin and creator can delete a post | Aras Güngöre | Not started |
|Use Cases related to the feedback system| Feedback system (post reporting or approval) are already covered | - | Duplicate|
|Use Cases related to Filter and sort activities| user can filter and sort activities | Ramazan Burak Sarıtaş | Needs Revision |,
|Approve/reject reports| Admin can investigate reported posts and users| Mehmet Emin İpekdal | in-progress |,
|Canceling authentication/verification of users| Admin can inhibit accounts| Mehmet Emin İpekdal | in-progress |,
|List logs by filter for admins| Admin can filter logs (included in filter & sort use case diagram) | Ramazan Burak Sarıtaş | Needs Revision |,
|Notification related use cases| Authenticated user can create notif tags| Begüm arslan |N/A|,
### Deadline of the Issue

05.04.2023

### Reviewer

@bgmrsln

**Comment by mehmetkuzu** [comment]
Put the list table with initial elements. 
Any line can be deleted or changed.

**Comment by mervegrbz** [comment]
I changed 
``` Resource Entry by guest ```  since it is not valid 😅 
``` Need Entry by guest ``` also is not valid

**Comment by mervegrbz** [comment]
I think we should be more precise and clear about use case
Use Cases related to a posted activity 
I changed this to 
approve/reject a post (post can be resource need event) 
follow a post/ want notification about post.
edit post
report post to the admin 
delete post (can be done by admin and creator of post)

**Comment by mehmetkuzu** [comment]
Please check the "admin users edit profile information of other users" UC. Should be possible or not? (I think we need this type of thing.)

**Comment by halilgurbuz** [comment]
> I changed
> `Resource Entry by guest` since it is not valid 😅
> `Need Entry by guest` also is not valid

@mervegrbz Second one seems valid based on the following requirement:
1.1.3.4 Users shall be able to create needs.

Should the requirement be updated?

**Comment by rburaksaritas** [comment]
I combined a few use cases related to filter & sort functionalities here: https://lucid.app/lucidchart/67d9f652-dcdf-4f1b-bc23-7fe323dac3aa/edit?invitationId=inv_66fa75ff-0e3d-4085-9ee1-5d04d27b3da9&page=0_0#

Can someone review and close #88 if the diagram is okay?

**Comment by rburaksaritas** [comment]
Does "Report post's owner to the admin | @bgmrsln" and "Approve/reject reports | @mehmeteminipekdal" include "Use Cases related to the feedback system"? I am asking because it's unassigned, and wondering if 1.2.2.2 is included?

>  1.2.2 Feedback System
>   - 1.2.2.1: The system shall allow users to report malicious users and activities.
>   - 1.2.2.2: The system shall allow users to check for a number of other users' confirmations or rejections about users, activities.
>   - 1.2.2.3: The system shall carry on reports to the administration system.
>   - 1.2.2.4: The system shall not accept the restricted accounts to register again.

**Comment by mervegrbz** [comment]
We have done all the listed use cases so I am closing the issue.

> Does "Report post's owner to the admin | @bgmrsln" and "Approve/reject reports | @mehmeteminipekdal" include "Use Cases related to the feedback system"? I am asking because it's unassigned, and wondering if 1.2.2.2 is included?
> 
> > 1.2.2 Feedback System
> > 
> > * 1.2.2.1: The system shall allow users to report malicious users and activities.
> > * 1.2.2.2: The system shall allow users to check for a number of other users' confirmations or rejections about users, activities.
> > * 1.2.2.3: The system shall carry on reports to the administration system.
> > * 1.2.2.4: The system shall not accept the restricted accounts to register again.

Yes I think feedback system contains the reporting.
