### ISSUE TITLE
Updating the Requirements

### ISSUE THREAD

**Issue by higurbuzz** [bounswe/bounswe2023group2#780]
### Issue Description

Requirements should be updated based on our discussions.

### Deadline of the Issue

24.12.2023

### Reviewer

Mehmet Kuzulugil

**Comment by egecans** [comment]
We revised and updated requirements with @higurbuzz

**Comment by higurbuzz** [comment]
In addition, although we updated the requirements before the final report, we discussed the requirements after milestone 2 on issue #661 .
