### ISSUE TITLE
Deployment - Annotation Service in a seperate container

### ISSUE THREAD

**Issue by mehmetkuzu** [bounswe/bounswe2023group2#784]
### Issue Description

AS related changes/writings in docker configuration should be done. 

### Deadline of the Issue

22.12.2023

### Reviewer

Halil İbrahim Gürbüz

**Comment by mervegrbz** [comment]
@mehmetkuzu  wrote the dockerfile and updated docker compose and I deployed the container, closing the issue 🚀
