### ISSUE TITLE
Update Requirements With New Term "Activity"

### ISSUE THREAD

**Issue by cahidenes** [bounswe/bounswe2023group2#80]
### Issue Description

Following #66, texts where resource, need, event, and activity occur will be replaced with the general name **Activity**.

### Deadline of the Issue

06.04.2023

### Reviewer

None

**Comment by arasgungore** [comment]
I have changed the term 'information' with the term 'activity' in requirements.

**Comment by HasanBingolbali** [comment]
@arasgungore requirements looks more clear now, closing the issue
