### ISSUE TITLE
Mobile - Search Implementation

### ISSUE THREAD

**Issue by egecans** [bounswe/bounswe2023group2#802]
### Issue Description

Search for all activities should be implemented on Mobile. After the user searches that activity, results fetched from the backend should be listed in the recycler view as the filter does.

### Deadline of the Issue

24.12.2023

### Reviewer

Egecan Serbester

**Comment by HasanBingolbali** [comment]
implemented with https://github.com/bounswe/bounswe2023group2/pull/872
