### ISSUE TITLE
Revising Notification Related Requirements 

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#81]
### Issue Description

The use case of notifications should be clarified for mockups and diagrams.

### Deadline of the Issue

4.4.23

### Reviewer

Merve Gürbüz

**Comment by bgmrsln** [comment]
User req
* 1.1.3.5 Users should be able to receive notifications about available resources, or actions taken in their area.(at what level) -> 1.1.3.5. Users should be able to receive notifications about certain topics based on location.(topic will be explained on glossary)
* 1.2.3.6 Users shall be able to search a resource, event or action, and receive results semantically related to the search (already exists)
   * 1.2.3.6.1. Users should be able to subscribe to a topic based on thier filter and search

System Req
* 1.2.10.2: The system should be able to create notifications, if they click “want to be notified” button on information. -> 1.2.10.2: The system should create notifications, if they click “want to be notified” button on information filter and search.
* 1.2.10.3: The system should be able to create notifications if users' profession might be implying that they can be a resource to a certain need. (exists)
 * 1.2.10.3.1: system should be able to add resource | translator | any topic to notification settings as default when user have a role 
* 1.2.10.4: The system should be able to create notifications if an event takes place near users' addresses when they provide their addresses. (exists)
 * 1.2.10.4.1 system should be able to add event | any | (user's city) topic to notification settings as default.
will add topic to glossary: (activity | type | location) ex: need | food | Istanbul

**Comment by bgmrsln** [comment]
Can you review it @mervegrbz?

**Comment by mervegrbz** [comment]
Which term will we use  ` topic ` or ` tag `  for notifications? Other than that thank you 🚀

**Comment by bgmrsln** [comment]
* Users should be able to add and delete topic/tag for notifications.
* Users should be able to view details or dismiss when they click on a notificaiton

**Comment by bgmrsln** [comment]
Added the mentioned [requirements](https://github.com/bounswe/bounswe2023group2/wiki/Requirements/_compare/bec986aafc7c3d40acf1049280be6be26396f632...cf3c1a8de4e6b7d836f6e36d8590b094c792558b). Can you close the issue?

**Comment by mervegrbz** [comment]
we updated requirements and implements the diagrams. Thanks a lot @bgmrsln
