### ISSUE TITLE
Creating Use Case Diagrams for Registration

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#82]
### Issue Description

Use case diagrams of registration process should be draw.

### Deadline of the Issue

04.03.23

### Reviewer

Egecan Serbester

**Comment by mervegrbz** [comment]
Can you  provide the link?

**Comment by bgmrsln** [comment]
I am adding [here](https://lucid.app/lucidchart/12dfcb9b-df14-4b9f-a228-58b117165a21/edit?page=0_0&invitationId=inv_eb5a9dec-6758-462e-9dcd-2490f1c1a6f1#)

**Comment by egecans** [comment]
I edited the use-case diagram of register, login and logout. Please check them out. I also will add some requirements according to these use cases. I will state them under the reviewing requirements [issue](https://github.com/bounswe/bounswe2023group2/issues/75)

**Comment by bgmrsln** [comment]
I believe these are enough. Should we close the issue?

**Comment by bgmrsln** [comment]
I believe these are enough. 
<img width="345" alt="image" src="https://user-images.githubusercontent.com/53114791/230889545-42725bce-c001-4db8-990a-c9bb2b391eeb.png">
Closing the issue.
