### ISSUE TITLE
User Manual: Instructions for how to use the system.

### ISSUE THREAD

**Issue by mehmetkuzu** [bounswe/bounswe2023group2#821]
### Issue Description

User Manual will be prepared.

### Deadline of the Issue

28.12.2023

### Reviewer

Merve Gürbüz

**Comment by canbora** [comment]
I will be preparing the User Manual for the website.

**Comment by egecans** [comment]
I did a User Manual with screenshots and explanations of our mobile app.

**Comment by egecans** [comment]
I closed the issue since deadline was over

**Comment by canbora** [comment]
The user manual for the website can be reached [here](https://docs.google.com/document/d/1YhTj1E6mnv9GsCxyLhpWH1aUKwuvzTOz/edit)
