### ISSUE TITLE
Backend - Sort by Reliability

### ISSUE THREAD

**Issue by higurbuzz** [bounswe/bounswe2023group2#828]
### Issue Description

Sort by reliability should be provided instead upvote/downvote count.

### Deadline of the Issue

24.12.2023

### Reviewer

None

**Comment by rburaksaritas** [comment]
See #894.

### Overview
This PR adds a `reliability` field to the _get all_ method responses of `resources`, `needs`, and `events`. The reliability score is calculated based on the upvotes and downvotes for each item. It is used to assess the credibility and trustworthiness of the information provided by users.

### Reliability Score Calculation
The reliability score is calculated using the Wilson Score Interval, a statistical method that takes into account the proportion of upvotes to total votes while considering the %95 confidence interval.  The formula is: 

```
z = 1.96  # 95% confidence interval
phat = upvotes / total_votes
reliability = (phat + z^2 / (2 * total_votes) - z * sqrt((phat * (1 - phat) + z^2 / (4 * total_votes)) / total_votes)) / (1 + z^2 / total_votes)
```

- `upvotes`: The number of upvotes for the item.
- `downvotes`: The number of downvotes for the item.
- `total_votes`: The total number of votes (upvotes + downvotes).

The reliability score ranges from 0 to 1, with higher values indicating higher reliability. Items with more upvotes and a higher proportion of upvotes to total votes will have a higher reliability score, reflecting greater trustworthiness.

### Sorting
To sort by reliability, simply add `sort_by=created_at&order=desc` or `sort_by=created_at&order=asc` to the query.
