### ISSUE TITLE
Creating Action related use cases (Authenticated user)

### ISSUE THREAD

**Issue by mervegrbz** [bounswe/bounswe2023group2#85]
### Issue Description

Authenticated users have many use cases regarding actions which has a considerable role in our app. 
- view actions
- delete actions
- create 
- report 
...

### Deadline of the Issue

03.04.2023

### Reviewer

Merve Gürbüz

**Comment by cahidenes** [comment]
I drew the action-related use cases. 
It would be amazing if someone could review the work that I have done. I might have misunderstood the use case concept or missed some ideas.
I intentionally dropped report because I thought it it more appropriate to report users from profile (not actions)

**Comment by cahidenes** [comment]
It is reviewed and merged.
