### ISSUE TITLE
Backend verification for votes

### ISSUE THREAD

**Issue by busetolunay** [bounswe/bounswe2023group2#852]
### Issue Description

Need and resources can be verified by admins and credible users , changes needed in resource need and feedback related files.

### Deadline of the Issue

24.12.2013

### Reviewer

@bgmrsln

**Comment by bgmrsln** [comment]
Can you please fix the entity fileds for unvote. They are not deleted(number and other fields): 
<img width="422" alt="image" src="https://github.com/bounswe/bounswe2023group2/assets/53114791/713c968a-369b-4b89-8494-18f7e204cc7d">

**Comment by busetolunay** [comment]
Fixed it with Begum.
