### ISSUE TITLE
Create Notification Related MockUps

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#86]
### Issue Description

Notification related mockups for the web page will be created. Two mockup page is being planned. Profile page is planning to extend as "ACCOUNT" and it will have three sub pages as "Profile Settings" , "Notification Settings", "User Activities". This will be prepared in order to understand notification requirments better. Notification requirements are not a must, so this mockup is not a definite desicion.

### Deadline of the Issue

04.04.23

### Reviewer

Mehmet Kuzulugil

**Comment by mehmetkuzu** [comment]
So I will review and finalize it (confirm) and close the issue?

**Comment by bgmrsln** [comment]
I added an overview(account) web page with has three sub pages in it: My Profile, Notifications, User Activities. I created another mockup for subpage Notifications and two mock up for notification.

**Comment by bgmrsln** [comment]
Can you review it @mehmetkuzu

**Comment by mehmetkuzu** [comment]
:-) just written. Ok.

**Comment by mehmetkuzu** [comment]
Seems ok.

**Comment by bgmrsln** [comment]
Then can you close the issue? we can discuss it further on the next meeting?
