### ISSUE TITLE
Creating Use Case Diagrams for Filter & Sort

### ISSUE THREAD

**Issue by rburaksaritas** [bounswe/bounswe2023group2#88]
### Issue Description

Use case diagrams for filter and sort functionalities should be drawn.

### Deadline of the Issue

9.04.2023

### Reviewer

Ramazan Burak Sarıtaş

**Comment by mervegrbz** [comment]
Can you provide a link to us? So we can collect start to collect diagrams

**Comment by rburaksaritas** [comment]
Here is the current diagram i prepared for filter and sort use cases: https://lucid.app/lucidchart/67d9f652-dcdf-4f1b-bc23-7fe323dac3aa/edit?viewport_loc=-57%2C-1192%2C3855%2C2224%2C0_0&invitationId=inv_66fa75ff-0e3d-4085-9ee1-5d04d27b3da9

@mervegrbz can you revise it?

**Comment by mervegrbz** [comment]
we have completed the use cases according to filter and sort, closing the issue.
