### ISSUE TITLE
User Profile Use Case Diagrams (Authorized and Role-Based )

### ISSUE THREAD

**Issue by mervegrbz** [bounswe/bounswe2023group2#89]
### Issue Description

User can be able to:
- view their  own activities.
- view others profiles
- edit own nformation
- report malicious user
- add a role 
- add certificate
...

### Deadline of the Issue

08.04.2023

### Reviewer

Begüm Arslan

**Comment by mehmetkuzu** [comment]
first shot. Please check if ok. (Will continue with this)
<img width="709" alt="image" src="https://user-images.githubusercontent.com/46297916/230442381-196fae36-9b9d-401b-8bdc-a45a506da809.png">

**Comment by mehmetkuzu** [comment]
https://lucid.app/lucidchart/00140af7-37b8-4f24-bad4-74643a5f3496/edit?viewport_loc=-279%2C88%2C2444%2C1060%2Cg0wMQdBSFgIJ&invitationId=inv_fd6fd5c2-4954-4d4e-b04e-70e8738481c3

Link is here

**Comment by mehmetkuzu** [comment]
First draft is done.
To be reviewed @bgmrsln

**Comment by bgmrsln** [comment]
Can you check #97? I think we can merge the two. It intersects a litte with your work but I created the issue for notifications and to put a higher level. We can work on them together. Also are you sure about the direction of includes arrows?

**Comment by mehmetkuzu** [comment]
Thanks. You are right about the directions of arrows. Changing now.

**Comment by mervegrbz** [comment]
We have done this part. We also joined this to the others. Thanks a lot.
