### ISSUE TITLE
Mobile - Annotations

### ISSUE THREAD

**Issue by cahidenes** [bounswe/bounswe2023group2#903]
### Issue Description

Descriptions of the activites should be kept using annotation server.

### Deadline of the Issue

26.12.2023

### Reviewer

None

**Comment by egecans** [comment]
It seems good for mobile, we annotate type and subtypes of activities as like this: Special thanks to you to handle that.

https://github.com/bounswe/bounswe2023group2/assets/87999176/cae69d5b-6956-431e-a921-c977c17d227e
