### ISSUE TITLE
Use cases for main page

### ISSUE THREAD

**Issue by mervegrbz** [bounswe/bounswe2023group2#92]
### Issue Description

Main page is the place that most of the function can be reached: 
-  Create emergency
- Go to map
- filter and sort
... 

This use case "view ain page" is more like connecting the dots so it would be better to wait for other use cases to be done.

### Deadline of the Issue

08.04.2023

### Reviewer

Begüm Arslan

**Comment by egecans** [comment]
When will it be completed? I will create a use case to view the main page (or dashboard), but the current mock-up isn't sufficient to think. @arasgungore

**Comment by mervegrbz** [comment]
We have added main page use cases closing the issue
