### ISSUE TITLE
Mockups for Sort filter feature

### ISSUE THREAD

**Issue by mervegrbz** [bounswe/bounswe2023group2#93]
### Issue Description

We did not show the filter options, how we will display activities filtered and sorted and when we clicked an activity what we will see. 

### Deadline of the Issue

08.04.2023

### Reviewer

Merve Gürbüz

**Comment by arasgungore** [comment]
I have added mockups for sorting by date and filtering by location for resources for now. Should I add more ways of sorting/filtering for resources or other activity types?
