### ISSUE TITLE
Creating resource related use cases

### ISSUE THREAD

**Issue by halilgurbuz** [bounswe/bounswe2023group2#94]
### Issue Description

I will work on resource related use cases, such as:

- create
- edit
- delete
- approve/reject

### Deadline of the Issue

10.04.2023

### Reviewer

Merve Gürbüz

**Comment by halilgurbuz** [comment]
Can you review and close if ok @mervegrbz ?

**Comment by mervegrbz** [comment]
Good work. you also worked on merging this use cases to the the whole use case diagram. Thanks a lot.
