### ISSUE TITLE
Software design documents (using UML)

### ISSUE THREAD

**Issue by mervegrbz** [bounswe/bounswe2023group2#941]

**Comment by azizamankenova** [comment]
I have made changes to the UML class diagram. The final version can be found [here](https://github.com/bounswe/bounswe2023group2/wiki/Class-Diagrams).

**Comment by rburaksaritas** [comment]
New Sequence Diagrams can be found [here](https://github.com/bounswe/bounswe2023group2/wiki/Sequence-Diagrams).
