### ISSUE TITLE
Use cases for Account Page

### ISSUE THREAD

**Issue by bgmrsln** [bounswe/bounswe2023group2#97]
### Issue Description

In the account page any user can view some part of the profile info and user activities. The user that has the profile can view and edit all of the profile info and the notifications and user activities.
* view personal account page
  * view notifications
    * edit notifications
  * view profile page
    * edit profile page
  * view user acitivities
    * edit user activities
* view other account page
  * view profile
  * view user activities

### Deadline of the Issue

10.04.2023

### Reviewer

Ömer Şahin Albayram

**Comment by mervegrbz** [comment]
This use case has finished
